### ISSUE TITLE
upload animated GIF

### ISSUE THREAD

**Issue by mortezakarimi** [verot/class.upload.php#10]
How to upload animated gif?
i need to upload animated GIF

**Comment by verot** [comment]
The class does not support animated GIFs

**Comment by mortezakarimi** [comment]
So, you don't decide to add support animated GIFs anymore?!

**Comment by verot** [comment]
Support for animated GIFs would require a complete rewrite of the class. It is not worth it, the class is too old. But feel free to submit a patch!
