### ISSUE TITLE
Original file deleted when process file from path

### ISSUE THREAD

**Issue by bastiankhalil** [verot/class.upload.php#102]
version: `verot/class.upload.php": "dev-master`

Using the class with path option, moves the original file (instead of copy) anyway to avoid this?

`
// image migration script
 public function imageUpload($folder, $uploadedFile)
    {
        $generated_uniq_name = $this->struuid(true);
        $thumb_options = $this->container->get('thumbs_settings');
        $dist_root = $this->container->get('upload_directory') . "/" . $folder . "/";
        $original_dist = $dist_root . "original/";

        $handle = new \upload($uploadedFile);
        if ($handle->uploaded) {
            $handle->dir_auto_create = true;
            $handle->file_new_name_body = $generated_uniq_name;

            // upload original
            $handle->process($original_dist);

            //process thumbs
            foreach ($thumb_options as $optionKey => $option) {
                $thumb_folder_name = $optionKey;
                $target_path = $dist_root . $thumb_folder_name . "/";
                $handle->file_new_name_body = $generated_uniq_name;
                $handle->image_resize = true;

                if ($option['crop']) {
                    $handle->image_ratio_crop = true;
                    $handle->image_y = $option['crop'];
                    $handle->image_x = $option['crop'];
                    $handle->process($target_path);

                    if ($handle->processed) {
                         echo 'image resized';
                    } else {
                        echo 'error : ' . $handle->error;
                    }

                } else {
                    if ($option['width']) {
                        $handle->image_x = $option['width'];
                        $handle->image_ratio_y = true;
                    }

                    if ($option['height']) {
                        $handle->image_y = $option['height'];
                        $handle->image_ratio_x = true;
                    }
                    $handle->process($target_path);

                    if ($handle->processed) {
                        echo  "image reside";
                    } else {
                        echo 'error : ' . $handle->error;
                    }
                }

            }

        }

        $handle->clean();
    }
`

**Comment by verot** [comment]
Please provide a log and a code sample.

**Comment by bastiankhalil** [comment]
@verot I am using it to migration some images. even the simple example from the script homepage, "move" the image not copy it!

**Comment by verot** [comment]
Remove `$handle->clean();` if you wish to keep the file.
