### ISSUE TITLE
add example with crop information provided by user

### ISSUE THREAD

**Issue by peterdd** [verot/class.upload.php#106]
Use case: Users do photos during event, but only interesting parts are wanted, for instance a blog article.

1. user chooses image file, see https://caniuse.com/#feat=input-file-accept
2. image shown in browser before sending the form (with HTML5 File API)
3. user can optional set a cropping rectangle ((x1,y1) and (x2,y2) coordinates within the image)
4. user submits and image is cropped and stored.

I have point 2 working (+ some validation client and server side)
point 3 should be not too hard.

**Comment by verot** [comment]
This is quite beyond the scope of the class.
