### ISSUE TITLE
Rename 'Image local manipulation' in test/index.html

### ISSUE THREAD

**Issue by peterdd** [verot/class.upload.php#107]
Using 'local' there is a bit ambiguous. Maybe distinguish between client/web browser side vs. web server side path or server file or something like that.

With HTML5 canvas it is possible to manipulate an image before doing the real upload. So with this possibility today we should distinguish between that 2 variants.

**Comment by verot** [comment]
I think "local" is not too bad. The class is in PHP, and is always working server-side anyways. And in the documentation, "local" is also used.
