### ISSUE TITLE
Cropping not working

### ISSUE THREAD

**Issue by colonna-mike** [verot/class.upload.php#11]
I have a PHP page that uses `php_class_upload`. All works well except that I'm having issues with cropping.

I pass the Left, Top, Right, and Bottom values all values come across (no issues here)

Log:
>[27-Aug-2015 19:31:40 America/Chicago] top 52 ,right 239 , bottom 172 ,left 119

What I'm trying to accomplish is resize the image then crop it.

I have set up the following code for php_class_upload:

     $foo->file_new_name_body =  $new_image_name;
     $foo->image_resize = true;
     $foo->image_x = $_width;
     $foo->image_ratio_y = true;
     $foo->image_convert = png;
     $foo->Process( $structure);
     $foo->image_rotate = $rotate;      
     $foo->image_crop = array($top ,$right,$bottom,$left); //  'T R B L'.

The image uploads okay and its resizes correctly. however the cropping is not applied. 
(just a note, I want the crop after the resize)

I also tried to hard code the vales  like below
     $foo->image_crop = '5 40 10% -20';
     $foo->image_crop = array( 0,100,100,0);
     $foo->image_crop = '0,100,100,0';

I think my issue is how I'm setting up the array but I'm at a point where I need help. Any help at all would be greatly appreciated.

**Comment by verot** [comment]
_image_crop_ and _image_rotate_ must be set before calling _process()_.

Besides, it should be:
``$foo->image_crop = array($top, $right, $bottom, $left); //  'T R B L'``

**Comment by colonna-mike** [comment]
Thank you, I see the type-O and I fixed that. All is being call before process(). But still no crop.. if you have any more suggestions that could help it would be appreciated.

**Comment by colonna-mike** [comment]
Just another note here is how 8m calling the process  function  it's paasi g back true and the rest of procedure is working.

if ($foo->processed) {
....
}

**Comment by verot** [comment]
Can you print out the log produced by the class? It will tell you everything the class does
