### ISSUE TITLE
Type webp

### ISSUE THREAD

**Issue by quinhone** [verot/class.upload.php#117]
It would be interesting to put the new default webp images
jpg to webp
png to webp

**Comment by verot** [comment]
You are right. I have implemented WebP support, commit is 2bed84e ans is now in _master_

Does it work for you?

**Comment by jenokizm** [comment]
Hey. what is it for you? how much saves space and quality?

**Comment by HMachiavelli** [comment]
It works for me, but the image does not resize in webp format.

https://branvo.s3.amazonaws.com/shop/branvo/testewebpp.webp
https://branvo.s3.amazonaws.com/shop/branvo/testewebpm.webp
https://branvo.s3.amazonaws.com/shop/branvo/testewebpg.webp

Those should be 3 images with different sizes. In my code, images are been saved with 250px, 500px and 1000px, but the result is allways the same.

Any hints?

**Comment by verot** [comment]
Can you copy here the log produced by the class?

**Comment by zanderwar** [comment]
Fair warning on WebP support: https://caniuse.com/#feat=webp
