### ISSUE TITLE
0 byte files rejected as Incorrect File Type

### ISSUE THREAD

**Issue by zanderwar** [verot/class.upload.php#118]
Uploading a .txt file of size 0 bytes periodically returns "Incorrect file type"

Is this intended? I understand it's unorthodox to upload a file with nothing in it but none-the-less the mime type is valid and should be allowed through

**Comment by verot** [comment]
On my system, such an empty file has a MIME of `inode/x-empty`. 

If you wish to accept such files, you can add it to the `$allowed` array of MIME types.

**Comment by zanderwar** [comment]
Right, agreed that it does come through with that mime-type, thanks @verot
