### ISSUE TITLE
Cropping Photos

### ISSUE THREAD

**Issue by truecastdesign** [verot/class.upload.php#123]
I really like your image processor and uploader you built. Great job.

I'm uploading profile photos with it and I would like them to be square images after I'm done processing them with the longest dimension being cropped top the short dimension. Do I need to calculate the longest dimension, subtract the short dimension, and divide that in two, then use the crop method? Is there a build-in way to do that?

Thanks

**Comment by verot** [comment]
You need to get your image dimensions (you can read `image_src_x` and `image_src_y` to infer the shortest dimension), and then you can do something like this:

```
$foo->image_resize          = true;
$foo->image_ratio_crop      = true;
$foo->image_y               = $short_dimension;
$foo->image_x               = $short_dimension;
```
