### ISSUE TITLE
Add  more mime types

### ISSUE THREAD

**Issue by SpiderNeo1** [verot/class.upload.php#129]
Hello, 
First of all thank you for everything you do, it's really amazing !

I just saw that when I transform XLSX files into CSV with Microsfot Excel into semicolon separator, that the "mime type" became **text/x-c** instead of **text/csv**.

Suddenly it is automatically refused during the upload.

When searching, there are even other mime types for CSV files like : 
**text/x-c**
**text/x-csv**
**text/comma-separated-values**
**text/x-comma-separated-values**
**application/csv**
**application/x-csv**

Currently, to allow them, I have to add them manually in `$handle->allowed[]`

Could you add them by default in your class?

Thank you.

**Comment by verot** [comment]
Added in fc9427a

**Comment by jenokizm** [comment]
Hi, where does the image and the excel? Are you crazy?

**Comment by verot** [comment]
What do you mean? I don't understand your message...

**Comment by jenokizm** [comment]
Well, your library is designed to upload photos, respectively, they type **image/jpeg** and etc. Then where does the excel?

**Comment by verot** [comment]
The library is designed to upload files primarily. Images, Excel files, etc... And then, if they are images, you can process them.
Do you have an issue uplading Excel files?

**Comment by jenokizm** [comment]
wow, how many years I use the first time I hear this. well there is that okay, always thought only for photos

**Comment by verot** [comment]
Well, the class is called "class.upload.php", isn't it? ;)

**Comment by jenokizm** [comment]
yes, but I still thought why so)
