### ISSUE TITLE
Can't upload without setting "action" on form

### ISSUE THREAD

**Issue by ripfoghorn** [verot/class.upload.php#13]
when using ``$_SERVER['REQUEST_METHOD'] == 'POST'`` to handle my POST requests I simply can't instantiate a new object but I can grab my ``$_FILES`` normally (I thought thats basically what it needs to make a new object) why is that?

**Comment by verot** [comment]
I am not sure to understand what you mean...

**Comment by ripfoghorn** [comment]
I'm using a class to handle my POST requests, on my class <code>__construct</code> I validate wheter or not it's actually a POST and then I use a function to call your class and instantiate a new object.
The problem is... it doesn't seem to work at all, the only way I could get it to work was to make another form calling another class (lets say upload.php) on its <code>action</code> attribute, using upload.php I could finally get to instantiate a new Upload object.
A little bit clearer now?
I can get my <code>$_FILES</code> using both ways

**Comment by verot** [comment]
Can you copy here the relevant part of your code? You should be able to instantiate the class anywhere in your code. Can you also print out the log produced by the class?

**Comment by ripfoghorn** [comment]
![help](https://cloud.githubusercontent.com/assets/5684406/9616405/493caf14-50d4-11e5-8758-20b73038a59e.png)

here you go buddy!

**Comment by verot** [comment]
Thank you for the code. It all looks fine. Can you print out the log from the class? Call ``$handle->log`` after calling ``Process()``

**Comment by ripfoghorn** [comment]
Unfortunately not at the moment, I'll do it tomorrow!

**Comment by ripfoghorn** [comment]
Used <code>die(var_dump($handle))</code> and <code>die(var_dump($handle->log))</code>
As it seems, the object doesn't get instantiated at all...

**Comment by ripfoghorn** [comment]
also did basic validation
<code>
	private function ImageHandler()
	{
		include('_tools/upload/class.upload.php');

	    if(isset($_FILES['test']))
	    {
	    	$handle = new Upload($_FILES['test']);
	    	die(var_dump($handle); //<<< my application dies here anyway 
		}
		else
		{
			die(var_dump('test'));
		}
</code>

**Comment by verot** [comment]
I think you'd better do this
```
$handle = new Upload($_FILES['test']);
var_dump($handle);
die();
```
What do you get?

**Comment by ripfoghorn** [comment]
absolutely nothing, blank as ghost

**Comment by verot** [comment]
Can you try this, before the instantiation?
```
if (class_exists('Upload')) {
    die('exists');
} else {
    die('does not exists');
}
```

**Comment by ripfoghorn** [comment]
it exists man... it exists...

**Comment by verot** [comment]
Well, then I don(t know what's goign on. I would try to turn on error_reporting to the max, and try with a simple example, have it to work, and then move it into your class, etc... 

I am not sure what else I can do. However, if you send me a simple self-contained piece of code I can test easily, I'll have a look.

**Comment by ripfoghorn** [comment]
I've just identified the problem man, it was some sort of conflict with <code>spl_autoload_register </code>
when I manually required my class (that's calling your class) all went well

**Comment by verot** [comment]
OK, great, I am glad you fixed it.
