### ISSUE TITLE
Use of undefined constant IMG_WEBP - assumed 'IMG_WEBP

### ISSUE THREAD

**Issue by SpiderNeo1** [verot/class.upload.php#130]
Hello, 

I have this error on the version 1.0.7.

My PHP version is : 5.5.12

But the constant IMG_WEBP is available as of PHP 5.6.25 and PHP 7.0.10, respectively.

Can you just add this condition please ?

```
if (!defined('IMG_WEBP')) {
    define('IMG_WEBP', 32);
}
```

Thank you !

**Comment by verot** [comment]
Added in 89acf02
