### ISSUE TITLE
Small type in Readme

### ISSUE THREAD

**Issue by webbird** [verot/class.upload.php#131]
There is a little typo in your Readme.

$handle = new \verot\Upload\Upload($_FILES['image_field']);

should be:

$handle = new \Verot\Upload\Upload($_FILES['image_field']);

(Uppercase V in Verot.)

**Comment by verot** [comment]
Where do you see that? In **master**?

**Comment by verot** [comment]
Thank you! 9c8a04b

**Comment by webbird** [comment]
Just realized I posted a typo with a typo :D
