### ISSUE TITLE
MIME validation is not foolproof

### ISSUE THREAD

**Issue by zanderwar** [verot/class.upload.php#132]
As you may already be aware MIME-type is not 100% fool proof.

For example, shell-scripts such as .bat files are declared as being `application/bat` or `application/x-bat` however that's not entirely truthful in a lot of cases; their MIME is often interpreted as `application/octet-stream` which is allowed by default by this class as that MIME also represents other non-malicious files and/or _documents_.

I'd like to propose the ability to not only forbid certain MIME types (which already exists); but also have the ability to forbid certain extensions as a fallback safety net

`$upload->forbidden_extensions = array('bat', 'exe', 'svg', 'php', 'phtml', 'dll', 'wsdl');`

If a rookie were to accidentally open a bat file that a user uploaded; the malicious potential is endless and significant beyond repair.

**Comment by verot** [comment]
Yes, it would be a good addition. I have no time to do it now, but I have added it to my list. And I'll gladly accept a patch.

**Comment by halillusion** [comment]
Hi @verot,

This issue was fixed in the #160
