### ISSUE TITLE
get imgae from url

### ISSUE THREAD

**Issue by Theolodewijk** [verot/class.upload.php#133]
is it also possible to get an image from a url?

I have tried use the follow code but no luck so far.

```
$add_post_url = $image_url; // 'https://www.lc.nl/incoming/e5m6zi-201506114440.jpg/ALTERNATES/LANDSCAPE_768/201506114440.jpg';
$format = explode(".", $add_post_url);
$path = $themes_path . '/img/news-crawler/' . $chat_id . '/test/' . array_pop($format) . '';
copy('' . $add_post_url . '', ''  . $path . '');
$handle = new upload($path);
```

_Warning: copy(https://www.lc.nl/incoming/e5m6zi-201506114440.jpg/ALTERNATES/LANDSCAPE_768/201506114440.jpg): failed to open stream: HTTP request failed! HTTP/1.1 426 Upgrade Required in /home/theolodewijk/domains/theolodewijk.nl/public_html/themes/theolodewijk/news-crawler/test.php on line 75_

**Comment by verot** [comment]
No, the class can only work on local files (or uploaded files). You need to fetch the image beforehand, as in your code. But in your code, you are not actually fetching the image, since there is an HTTP error. Make sure your call to copy() actually retrieves the file.
