### ISSUE TITLE
The uploaded file exceeds the upload_max_filesize

### ISSUE THREAD

**Issue by ArtMin96** [verot/class.upload.php#134]
Hi there.
Thanks for this amazing script.

When I add a new image, I get a response every time "File upload error (the uploaded file exceeds the upload_max_filesize directive in php.ini)." even when my file size is 65KB.
Also, that's my php.ini config

;default_socket_timeout      = 60
max_execution_time           = 800
max_file_uploads            = 20
;max_input_nesting_level     = 64
max_input_time              = 1000
;max_input_vars              = 1000
memory_limit                 = 1536M
post_max_size                = 700M
upload_max_filesize          = 700M

Can you help me, please?

**Comment by verot** [comment]
Hi. Please note that the issue tracker is not  support forum. As for the max file size, check the log produced by the class.
