### ISSUE TITLE
Photos Auto Rotating 

### ISSUE THREAD

**Issue by scottiericho** [verot/class.upload.php#135]
Hey there.

We are experiencing photos uploaded from a camera that are rotating when they shouldn't be. Swapping from portrait to landscape.

This is happening even IF we specify $handle->image_auto_rotate = false;

What else could be causing this to happen?

**Comment by verot** [comment]
Can you copy here the log produced by the class?

**Comment by scottiericho** [comment]
Sure thing. I can also email you the photo/jpg in question if desired?

system information
- class version : 03/08/2019
- operating system : Linux
- PHP version : 7.3.17
- GD version : 2.1.0
- supported image types : png webp jpg gif bmp
- open_basedir : no restriction
- upload_max_filesize : 16M (16777216 bytes)
- language : en_GB
source is an uploaded file
- upload OK
- file name OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    Fileinfo PECL extension not available
- Checking MIME type with UNIX file() command
    PHP exec() function is disabled
- Checking MIME type with mime.magic file (mime_content_type())
    mime_content_type() is not available
- Checking MIME type with getimagesize()
    MIME type detected as image/jpeg by PHP getimagesize() function
- MIME validated as image/jpeg
source variables
- You can use all these before calling process()
    file_src_name : tester.jpeg
    file_src_name_body : tester
    file_src_name_ext : jpeg
    file_src_pathname : /tmp/phpJ01DAw
    file_src_mime : image/jpeg
    file_src_size : 1213888 (max= 16777216)
    file_src_error : 0
- source file is an image
    image_src_x : 3000
    image_src_y : 2250
    image_src_pixels : 6750000
    image_src_type : jpg
    image_src_bits : 8
process file to ../../../content/images/gallery/
- file size OK
- file mime OK : image/jpeg
- file name body prepend : admin-
- file name safe format
- destination variables
    file_dst_path : ../../../content/images/gallery/
    file_dst_name_body : admin-tester
    file_dst_name_ext : jpeg
- checking for auto_rename
    auto_rename to admin-tester_2.jpeg
- destination file details
    file_dst_name : admin-tester_2.jpeg
    file_dst_pathname : ../../../content/images/gallery/admin-tester_2.jpeg
- admin-tester_2.jpeg doesn't exist already
- auto-rotate deactivated
- image resizing or conversion wanted
- source image is JPEG
- setting destination file type to jpg
- resizing...
    ratio_crop_x : 80 (40;40)
    image_src_x y : 3000 x 2250
    image_dst_x y : 320 x 240
    resized image object created
- crop image : 0 40 0 40 
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK
process file to ../../../content/images/gallery/
- file size OK
- file mime OK : image/jpeg
- file name body prepend : thumb-
- file name safe format
- destination variables
    file_dst_path : ../../../content/images/gallery/
    file_dst_name_body : thumb-tester
    file_dst_name_ext : jpeg
- checking for auto_rename
    auto_rename to thumb-tester_2.jpeg
- destination file details
    file_dst_name : thumb-tester_2.jpeg
    file_dst_pathname : ../../../content/images/gallery/thumb-tester_2.jpeg
- thumb-tester_2.jpeg doesn't exist already
- auto-rotate deactivated
- image resizing or conversion wanted
- source image is JPEG
- setting destination file type to jpg
- resizing...
    ratio_crop_x : 213 (107;106)
    image_src_x y : 3000 x 2250
    image_dst_x y : 853 x 640
    resized image object created
- crop image : 0 106 0 107 
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK
process file to ../../../content/images/gallery/
- file size OK
- file mime OK : image/jpeg
- file name safe format
- destination variables
    file_dst_path : ../../../content/images/gallery/
    file_dst_name_body : tester
    file_dst_name_ext : jpeg
- checking for auto_rename
    auto_rename to tester_2.jpeg
- destination file details
    file_dst_name : tester_2.jpeg
    file_dst_pathname : ../../../content/images/gallery/tester_2.jpeg
- tester_2.jpeg doesn't exist already
- auto-rotate deactivated
- image resizing or conversion wanted
- source image is JPEG
- setting destination file type to jpg
- resizing...
    ratio_crop_x : 426 (213;213)
    image_src_x y : 3000 x 2250
    image_dst_x y : 1706 x 1280
    resized image object created
- crop image : 0 213 0 213 
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK
tester_2.jpeg', 'active')

**Comment by verot** [comment]
According to the log, the class doesn't do any rotation. It is likely that your image is in fact already rotated, but you don't see it because the software you are using to view use rotates the image automatically.

**Comment by scottiericho** [comment]
We are using the Mac Preview app, and the photos were likely taken on an iPhone of some sort.

I just loaded it in photoshop and it looks fine. 

Can I send you the photo to try?

Scott

**Comment by verot** [comment]
Yes, please send.

**Comment by scottiericho** [comment]
Hey Colin,

Here you go.

Cheers,

Scott

**Comment by verot** [comment]
Where did you send it? You can send it to colin@verot.net

**Comment by verot** [comment]
Your image is indeed rotated. When you are opening it in Photoshop, it does auto-rotate it, resulting in a portrait picture.
Using the class, with $handle->image_auto_rotate = false does not rotate the image, and then you have the original paysage image. Try $handle->image_auto_rotate = true in order to have the image properly rotated as Photoshop does.

**Comment by scottiericho** [comment]
Hey Colin,

OK, after we enabled auto rotate it still wasn’t working. But the process log indicated we needed exif_read_data support. The entire EXIF module wasn’t enabled in PHP. 

So I enabled that and it fixed it!

Many thanks,

Scott

**Comment by elcarim** [comment]
https://i.paste.pics/e5dd9526cda08025b0f80ec77518b2eb.png

**Comment by verot** [comment]
Thanks; fixed.
