### ISSUE TITLE
Throw error if file source doesn't exists

### ISSUE THREAD

**Issue by Arsavin** [verot/class.upload.php#137]
If file source doesn't exists, nothing happen.
`$resizer = new Upload($image);`
How can I set Upload class throwing and error if source image doesn't exists?

**Comment by verot** [comment]
You need to check the variable `uploaded`, like this:

    $resizer = new Upload($image);
    if ($handle->uploaded) {
      // ....
      if ($handle->processed) {
        // ....
        $handle->clean();
      } else {
        echo 'error : ' . $handle->error;
      }
    } else {
      echo 'error : ' . $handle->error;
    }
