### ISSUE TITLE
Deprecated: Array and string offset access syntax with curly braces is deprecated in ...\class.upload.php on line 2726

### ISSUE THREAD

**Issue by xian04** [verot/class.upload.php#138]
I am using the library on my local machine using xampp. I was able to upload the images but when I turn on the PHP error reporting this message shows up. 
`Deprecated: Array and string offset access syntax with curly braces is deprecated in C:\xampp\htdocs\test\lib\class.upload.php on line 2726`. (Just annoyed me)

I am using PHP Version 7.4.7.

**Comment by verot** [comment]
Which version of the class are you using?

**Comment by xian04** [comment]
Hi @verot, I am not sure what version I am using. But I have tried to download the latest class and included on my program and it seems to work fine. So, maybe I am using the old version of it. The file was on my machine since 2018 I think. Anyway, thank you for this amazing library.
