### ISSUE TITLE
error : Destination directory can't be created. Can't carry on a process.

### ISSUE THREAD

**Issue by sinaboromand** [verot/class.upload.php#14]
Hi

why when i use "http://localhost/public/uploads/" for upload folder destination its not work and get error
but when i use "c:\wamp\www\public\uploads\" its work  -.- ?!?

plzzzz help me how to fix this.
too many thnx.

**Comment by verot** [comment]
You cannot use an HTTP destination for your call to `process()`, you can only use a real file path.
