### ISSUE TITLE
Unable to crop image correctly

### ISSUE THREAD

**Issue by exhaler** [verot/class.upload.php#140]
Hello, using cropper https://github.com/fengyuanchen/jquery-cropper to crop an image before upload. I'm storing the crop values as hidden input fields in the form to submit.

However i'm unable to figure out how to crop the image correctly according to the selection i'm doing.
```
$file->image_resize = true;
$file->image_x = ceil($image_details['width']);
$file->image_y = ceil($image_details['height']);
// try another approach 
$file->image_resize = true;
$file->image_crop = '$x, $width, $y, $height' // values for top, right, bottom and left
```

Both options don't work.

Thanks for the help

**Comment by verot** [comment]
You need to use `image_ratio_*` alongside `image_x` and/or `image_y`.

As for `image_crop`, it accepts an array as a value, or a space delimited list of values; in your code, you are separating values with commas

**Comment by exhaler** [comment]
So i should send image_crop these values
```
x: the offset left of the cropped area
y: the offset top of the cropped area
width: the width of the cropped area
height: the height of the cropped area
```

**Comment by verot** [comment]
`image_crop` values are the number of pixels removed on each side. Please check the [doc](https://github.com/verot/class.upload.php/), and the [demo](https://www.verot.net/php_class_upload_samples.htm).

**Comment by exhaler** [comment]
I'm still a bit confused, the cropper script gives me the top, left, width and height of the cropping box. But I passed those to the upload class I don't get the correct image
