### ISSUE TITLE
Possible PHP v8 Issues

### ISSUE THREAD

**Issue by dleffler** [verot/class.upload.php#144]
Since PHP v8 changes GD functions to return an object instead of a resource, there are 3 lines of code where 'imagedestroy()' would NOT be called which may or may not cause issues. HOWEVER, in PHP v8 imagedestoy() no longer does anything and should be replaced by an 'unset()' call .

The issue here is that php changed the behavior of GD. Instead of a resource that is returned, it's an instance of \GDImage object.
According to this site [](https://php.watch/versions/8.0/GDImage) (which is linked in the official Release announcement of php8), the solution is rather simple: Besides checking if the variable "is_resource" it is also necessary to check if variable is_object AND instance of \GDImage.

**Comment by verot** [comment]
Thank you. I have added checks for PHP 8 in 6cc2cbf5a132748f5386403807c3efcf3ba22a5c
