### ISSUE TITLE
String contains non ISO-8859-1 code point.

### ISSUE THREAD

**Issue by xkpx64** [verot/class.upload.php#147]
Hello how to repair this error for UTF8 filenames?

![Capture](https://user-images.githubusercontent.com/5773378/111635436-252cc280-8800-11eb-9d03-7c28626de8cb.PNG)

Error seems to happen here.
`<html>
		window.onload = function () {
		  function xhr_send(file, status, progress) {
			if (file) {
			  xhr.addEventListener('readystatechange', function(event) {
				if(xhr.readyState == 4){
				  document.getElementById(status).innerHTML = xhr.responseText;
				}
			  }, false);
				xhr.upload.addEventListener("progress", function (event) {
				if (event.lengthComputable) {
				  self.progress = event.loaded / event.total;
				} else if (this.explicitTotal) {
				  self.progress = Math.min(1, event.loaded / self.explicitTotal);
				} else {
				  self.progress = 0;
				}
				document.getElementById(progress).innerHTML = ' ' + Math.floor(self.progress*1000)/10 + '%';
				document.getElementById(progress).style.width=  self.progress*100 + '%';
			  }, false);
			  xhr.open("POST", "upload_handle.php?action=xhr");
			  xhr.setRequestHeader("Cache-Control", "no-cache");
			  xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
			  xhr.setRequestHeader("X-File-Name", file.name);
			  xhr.send(file);
			}
		  }
		  function xhr_parse(file, status) {
			if (file) {
			  document.getElementById(status).innerHTML = "<b>" + file.name + "(" + file.type + ", " + file.size + ") </b> / xkpJsCall";
			} else {
			  document.getElementById(status).innerHTML = "Не сте избрали файл!";
			}
		  }
		  var xhr = new XMLHttpRequest();
		  if (xhr && window.File && window.FileList) {
			// xhr example
			var xhr_file = null;
			document.getElementById("xhr_field").onchange = function () {
			  xhr_file = this.files[0];
			  xhr_parse(xhr_file, "xhr_status");
			}
			document.getElementById("xhr_upload").onclick = function (e) {
			  e.preventDefault();
			  xhr_send(xhr_file, "xhr_result", "xhr_progress");
			}
		  }
		}
    </html>`

**Comment by verot** [comment]
Can you try the new code on `master`?

**Comment by xkpx64** [comment]
Working Thank You Sir!
