### ISSUE TITLE
Issue with webp

### ISSUE THREAD

**Issue by icret** [verot/class.upload.php#148]
download https://github.com/verot/class.upload.php
used 'test' folder upload webp format 
show error:
File not uploaded on the server
Error: Can't read image source. Not an image?.

**Comment by icret** [comment]
https://i1.100024.xyz/i/2021/05/09/1117dkz.gif

**Comment by verot** [comment]
You have to make sure that your version of GD has webp support, and that PHP is compiled with GD support. Please note that the class is not supported on Windows (although it should work)

**Comment by icret** [comment]
thanks,already solved.
