### ISSUE TITLE
Image uploading on IIS(windows) results in tmp file in given directory

### ISSUE THREAD

**Issue by raizdev** [verot/class.upload.php#152]
Debian webserver works fine, when i switch to IIS the image stays at tmp file in upload directory.

**Comment by verot** [comment]
Please note that IIS is not officialy supported. But anyhow, can you paste here the log produced by the class?

**Comment by verot** [comment]
This is not really the log. You should output `$handle->log` after calling `process()`
Anyway, I think your problem is that you want to process a local file (in /tmp), and then wonder why the file remains in /tmp after being processed. It is normal behaviour, so that you can process a same file several times (for instance to produce several thumbnails).
In order to delete the original file, you need to call `clean()` after calling `process()`

**Comment by raizdev** [comment]
<b>system information</b><br />-&nbsp;class version: 03/08/2019<br/>-&nbsp;operating system: WINNT<br/>-&nbsp;PHP version: 8.0 .0<br/>-&nbsp;GD version: 2.1 .0<br/>-&nbsp;supported image types: png webp jpg gif bmp<br/>-&nbsp;open_basedir: no restriction<br/>-&nbsp;upload_max_filesize: 2 M(2097152 bytes)<br/>-&nbsp;language: en_GB<br/><b>source is a local file C: \Windows\Temp\php9FDC.tmp</b><br />-local file OK<br/><b>determining MIME type</b><br />-Checking MIME type with Fileinfo PECL extension<br/>&nbsp;&nbsp;&nbsp;&nbsp;Fileinfo PECL extension not available<br/>-Checking MIME type with UNIX file()command<br/>&nbsp;&nbsp;&nbsp;&nbsp;UNIX file()command not availabled<br/>-Checking MIME type with mime.magic file(mime_content_type())<br/>&nbsp;&nbsp;&nbsp;&nbsp;mime_content_type()is not available<br/>-Checking MIME type with getimagesize()<br/>&nbsp;&nbsp;&nbsp;&nbsp;MIME type detected as image/png by PHP getimagesize()function<br/>-&nbsp;MIME validated as image/png<br/><b>source variables</b><br />-You can use all these before calling process()<br/>&nbsp;&nbsp;&nbsp;&nbsp;file_src_name: php9FDC.tmp<br/>&nbsp;&nbsp;&nbsp;&nbsp;file_src_name_body: php9FDC<br/>&nbsp;&nbsp;&nbsp;&nbsp;file_src_name_ext: tmp<br/>&nbsp;&nbsp;&nbsp;&nbsp;file_src_pathname: C: \Windows\Temp\php9FDC.tmp<br/>&nbsp;&nbsp;&nbsp;&nbsp;file_src_mime: image/png<br/>&nbsp;&nbsp;&nbsp;&nbsp;file_src_size: 291412(max=2097152)<br/>&nbsp;&nbsp;&nbsp;&nbsp;file_src_error: 0<br/>-source file is an image<br/>&nbsp;&nbsp;&nbsp;&nbsp;image_src_x: 1000<br/>&nbsp;&nbsp;&nbsp;&nbsp;image_src_y: 343<br/>&nbsp;&nbsp;&nbsp;&nbsp;image_src_pixels: 343000<br/>&nbsp;&nbsp;&nbsp;&nbsp;image_src_type: png<br/>&nbsp;&nbsp;&nbsp;&nbsp;image_src_bits: 8<br/><b>process file to C: \inetpub\wwwroot\Cosmic\src\App\Controllers\Admin/../../../../public/uploads/\</b><br />-file size OK<br/>-file mime OK: image/png<br/>-new file name body: 61701 ee1a3197<br/>-file name safe format<br/>-destination variables<br/>&nbsp;&nbsp;&nbsp;&nbsp;file_dst_path: C: \inetpub\wwwroot\Cosmic\src\App\Controllers\Admin/../../../../public/uploads/\<br/>&nbsp;&nbsp;&nbsp;&nbsp;file_dst_name_body: 61701 ee1a3197<br/>&nbsp;&nbsp;&nbsp;&nbsp;file_dst_name_ext: tmp<br/>-checking for auto_rename<br/>-destination file details<br/>&nbsp;&nbsp;&nbsp;&nbsp;file_dst_name: 61701 ee1a3197.tmp<br/>&nbsp;&nbsp;&nbsp;&nbsp;file_dst_pathname: C: \inetpub\wwwroot\Cosmic\src\App\Controllers\Admin/../../../../public/uploads/\61701 ee1a3197.tmp<br/>-61701 ee1a3197.tmp doesn 't exist already<br />- auto-rotate requires function exif_read_data to be enabled<br />- no image processing wanted<br />- <b>process OK</b><br />{"status":"success","message":"News edit successfully"}
