### ISSUE TITLE
image resize not work

### ISSUE THREAD

**Issue by guraysatici** [verot/class.upload.php#155]
Hi, i trying this php code but it's not working to image resize code.. 
im trying this code : 

```
include("./incs/class.upload.php");
$handle = new \Verot\Upload\Upload($_FILES['Filedata']);
   if ($handle->uploaded) {
	$handle->file_new_name_body = $fileName;
	$handle->process($target);
          $imageOrg = $handle->file_dst_pathname;
	if ($handle->processed) {
		$handle->file_new_name_body = $fileName;
		$handle->file_name_body_pre = 'm_';
		$handle->image_resize = true;
		$handle->image_x = 400;
		$handle->image_ratio_y = true;
		$handle->process($target);
              $imageMdm = $handle->file_dst_pathname;
              if ($handle->processed) {
```

**Comment by verot** [comment]
Check the logs produced by the class

**Comment by ulziibadrakh-p** [comment]
Same problem before it was okey maybe some unexpected  update
```
foreach ($sizes as $key => $size) {
                    if ($crop) {
                        $handle->image_precrop = $crop;
                    }
                    $handle->image_resize = true;
                    $handle->image_ratio_y = true;
                    $handle->file_overwrite = true;
                    $handle->file_new_name_body = $option->name;
                    $handle->file_name_body_pre = $size;
                    $handle->image_x = $size;
                    $handle->process($path);
                }

                if ($handle->processed) {
                    $handle->clean();
```

**Comment by ulziibadrakh-p** [comment]
I have same problem. Nor errors. 
```
$handle->image_precrop = $crop;
                foreach ($sizes as $key => $size) {
                    $handle->image_resize = true;
                    $handle->image_ratio_y = true;
                    $handle->file_overwrite = true;
                    $handle->file_new_name_body = $option->name;
                    $handle->file_name_body_pre = $size;
                    $handle->image_x = $size;
                    $handle->process($path);
                }

                if ($handle->processed) {
                    $handle->clean();
```

**Comment by guraysatici** [comment]
> I have same problem. Nor errors. Precrop and resize not working
> 
> ```
> $handle->image_precrop = $crop;
>                 foreach ($sizes as $key => $size) {
>                     $handle->image_resize = true;
>                     $handle->image_ratio_y = true;
>                     $handle->file_overwrite = true;
>                     $handle->file_new_name_body = $option->name;
>                     $handle->file_name_body_pre = $size;
>                     $handle->image_x = $size;
>                     $handle->process($path);
>                 }
> 
>                 if ($handle->processed) {
>                     $handle->clean();
> ```

Hi, Please check that the GD library loaded... it was resolved after loadin the GD library..

**Comment by ulziibadrakh-p** [comment]
> > I have same problem. Nor errors. Precrop and resize not working
> > ```
> > $handle->image_precrop = $crop;
> >                 foreach ($sizes as $key => $size) {
> >                     $handle->image_resize = true;
> >                     $handle->image_ratio_y = true;
> >                     $handle->file_overwrite = true;
> >                     $handle->file_new_name_body = $option->name;
> >                     $handle->file_name_body_pre = $size;
> >                     $handle->image_x = $size;
> >                     $handle->process($path);
> >                 }
> > 
> >                 if ($handle->processed) {
> >                     $handle->clean();
> > ```
> 
> Hi, Please check that the GD library loaded... it was resolved after loadin the GD library..

Thank you. It works now :)
