### ISSUE TITLE
It seems the latest version still not work with gif file

### ISSUE THREAD

**Issue by alexwenbj** [verot/class.upload.php#156]
I found it said that this issue has been fixed in #50 ,but it seems the latest version still no work with gif.(Only upload, no any other manipulation such as crop/resize etc).Any other configure for gif file? Thank you.
```
if ($handle->uploaded) {
    $handle->file_new_name_body   = "content-" . date('YmdHisu');
    $handle->process($img_dir);
    if ($handle->processed) {
        $img = array("success" => 1, "message" => "upload success", "url" => $imgs_dir . '/' . $handle->file_dst_name);
        echo json_encode($img);
        $handle->clean();
    } else {
        // ...
    }
}
```

**Comment by verot** [comment]
You can display the log produced by the class, and it should provide you with more information about what is happening.

**Comment by alexwenbj** [comment]
OK, thank you.I will have a try.
