### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by Shou-nen** [verot/class.upload.php#157]
Is there a problem on PHP 8.1?

E_DEPRECATED | line 4042 | Implicit conversion from float 237.4 to int loses precision
E_DEPRECATED | line 4042 | Implicit conversion from float 235.4 to int loses precision

**Comment by verot** [comment]
I cannot test on 8.1 right now. But this woarning is not too problematic. The values should be explicitely cast as integer rather than implicitely converted, but the class will work just as well.

**Comment by wintstar** [comment]
I use class.upload.php under PHP Version 8.1.8 and have no entries in the error log of the server.

**Comment by verot** [comment]
> I use class.upload.php under PHP Version 8.1.8 and have no entries in the error log of the server.

What do you mean? What entries do you expect in the error log?

**Comment by wintstar** [comment]
I will say, i have no problems with php 8.1. No errors.

**Comment by verot** [comment]
Should be now fixed with 456535b
