### ISSUE TITLE
Upload class not Processing the File paramter i pass into it

### ISSUE THREAD

**Issue by abiodunjames** [verot/class.upload.php#16]
I namespace the upload class  and am instantiating like this \lib\upload\upload($file,$lang);
When i dump the result after passing my file in to it. It returns empty object after dump i.e It does not act on the file at all.

![verot 1](https://cloud.githubusercontent.com/assets/14722744/10410718/02e201cc-6f42-11e5-8000-b7db2960c32a.PNG)
![verot2](https://cloud.githubusercontent.com/assets/14722744/10410720/093f2ebe-6f42-11e5-861f-e65d489e2dfa.PNG)
![dumped](https://cloud.githubusercontent.com/assets/14722744/10410721/0bddd22e-6f42-11e5-9670-fedddae51e52.PNG)

<?php

$var= new \lib\upload\upload($_FILES['file']);

?>

**Comment by verot** [comment]
Rename and call the constructor explicitely, see #15
