### ISSUE TITLE
Cyrillic symbols encoding 

### ISSUE THREAD

**Issue by ad-Ham** [verot/class.upload.php#165]
Hello!
I'm trying to put Cyrillic text on a picture and get, I suppose, an encoding error. What should I do? 
![7beHRpo_Em0](https://user-images.githubusercontent.com/91159435/185813236-08639bfd-a491-4d92-922e-dad00adf49d5.jpg)

**Comment by verot** [comment]
Is your original text in UTF-8? And are you using a TTF font?

You need an appropriate TTF font, which includes the characters you need, in order to have them displayed. See f5a3ce97bfe61d28183be35bf167f6f3e76c0728

**Comment by ad-Ham** [comment]
> Is your original text in UTF-8? And are you using a TTF font?
> 
> You need an appropriate TTF font, which includes the characters you need, in order to have them displayed. See [f5a3ce9](https://github.com/verot/class.upload.php/commit/f5a3ce97bfe61d28183be35bf167f6f3e76c0728)

Yes, text is in UTF-8. I'm using Roboto font, it definitely has Cyrillic characters

**Comment by verot** [comment]
Can you provide a test case?

**Comment by ad-Ham** [comment]
Sorry, I imported my font incorrectly. That was the problem
