### ISSUE TITLE
Allowed video/* Doesn't Include MP4

### ISSUE THREAD

**Issue by parrycarry** [verot/class.upload.php#167]
I had actually fixed this myself when I was manually uploading class.upload.php, but I recently installed via Composer instead, so I figured I'd ask to get this fixed directly, especially for the sake of anyone else. I'm new to GitHub, so don't know the best practice to get fixes in...

Basically `$this->mime_types = array()` needs to also include `'mp4' => 'video/mp4',` so that `$handle->allowed = array('image/*', 'video/*');` can actually allow mp4 uploads.

**Comment by verot** [comment]
Fixed in 76866f3
