### ISSUE TITLE
image upload using FTP connection

### ISSUE THREAD

**Issue by AdmirTomaz** [verot/class.upload.php#17]
image upload using FTP connection it's possible?
my hosting server has 2mb upload limit, I could create a script to send the picture, use the class_upload to resize, use the resized image and erase the big picture?
What is the shipping method that uses class_upload?

Sorry for bad English

**Comment by verot** [comment]
If you wish to do that, you need to first transfer the image as you wish, via FTP for instance, and then you can use the class to process the file locally.
