### ISSUE TITLE
Multipart upload

### ISSUE THREAD

**Issue by icret** [verot/class.upload.php#173]
It seems that you haven't logged in to github for a long time, how are you doing recently?

I would like to ask whether this open source program supports multipart upload? According to my test, it seems that after the front-end enables multi-part upload, it may cause an exception? It may be that my technology is relatively poor and I didn't make good use of this program.

**Comment by verot** [comment]
I don't think the class is a good fit for multi parts uploads. It would be better done outside of the class.
