### ISSUE TITLE
Deprecation php8.2

### ISSUE THREAD

**Issue by nGuindet** [verot/class.upload.php#174]
I have this deprecation with php 8.2

Creation of dynamic property Verot\Upload\Upload::$file_max_size_raw is deprecated [in <b>vendor\verot\class.upload.php\src\class.upload.php</b>, line <b>1765

need to add 

    /**
     * Value of <i>upload_max_filesize</i> from php.ini
     *
     * @access public
     * @var string
     */
    var $file_max_size_raw;

**Comment by verot** [comment]
Please use the latest version, it has been fixed in 577a2959c

**Comment by nGuindet** [comment]
> Please use the latest version, it has been fixed in [577a295](https://github.com/verot/class.upload.php/commit/577a2959c898e5362ba4c7db03f18b3fccca6469)

Thanks, i don't see it on last tagged version and just post an issue ^^
