### ISSUE TITLE
Composer is not up2date

### ISSUE THREAD

**Issue by ThomasDev-de** [verot/class.upload.php#175]
Hi,

Under PHP8.2 I get the error:
`
Deprecated: Creation of dynamic property Verot\Upload\Upload::$file_max_size_raw is deprecated in /vendor/verot/class.upload.php/src/class.upload.php on line 1765`

I've seen that the bugs have been fixed, but I can't get the latest version through Composer.

Could you communicate the changes to the composer or do I have a local problem?

**Comment by verot** [comment]
You could do this to get the lastest version: `composer require verot/class.upload.php:dev-master`

But I have added tags, so now composer should pick up the latest version.
