### ISSUE TITLE
after converting image returns orginal file extension

### ISSUE THREAD

**Issue by nesyaz** [verot/class.upload.php#18]
hi verot
```php
$img_upload = new upload($_FILES['doska_img']);
$img_file_name = "doska_img".date("Ymdhis");
if ($img_upload->uploaded) {
  $img_upload->file_new_name_body   = $img_file_name;
  $img_upload->image_resize         = true;
  $img_upload->image_x              = 435;
  $img_upload->image_y              = 280;
  $img_upload->image_convert        = 'png';
  $img_upload->process($az_cms_file_upload_folder);
  if ($img_upload->processed) {
    $img_upload->clean();
  } else {
    echo 'error : ' . $img_upload->error;
  }
}
echo $img_upload->file_dst_ext == 'jpg'; //true
```

**Comment by verot** [comment]
Can you print out the logs produced by the class? Add this:
```
echo $img_upload->log
```

**Comment by nesyaz** [comment]
<form enctype="multipart/form-data" method="post" action="index.php">
  <input type="file" size="32" name="image_field" value="">
  <input type="submit" name="Submit" value="upload">
</form>
<br>

<?php

require 'vendor/autoload.php';

$handle = new upload($_FILES['image_field']);
if ($handle->uploaded) {
  $handle->file_new_name_body   = 'image_resized';
  $handle->image_resize         = true;
  $handle->image_x              = 100;
  $handle->image_ratio_y        = true;
  $handle->image_convert = 'png';
  $handle->process('/home/aysen/localhost/phptest/uploads/');
  if ($handle->processed) {
    echo 'image resized<br>';
    echo $handle->log;
    if ($handle->file_dst_name_ext == 'jpg') echo 'is jpg';
    $handle->clean();
  } else {
    echo 'error : ' . $handle->error;
  }
} else echo 'Please choose file';

?>

image resized
system information
- class version : 0.33dev
- operating system : Linux
- PHP version : 5.5.30-1+deb.sury.org~trusty+1
- GD version : GD not present
- supported image types : none
- open_basedir : no restriction
- upload_max_filesize : 2048M (2147483648 bytes)
- language : en_GB
source is an uploaded file
- upload OK
- file name OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    MAGIC path will not be used
    MIME type detected as image/jpeg; charset=binary by Fileinfo PECL extension
- MIME validated as image/jpeg
source variables
- You can use all these before calling process()
    file_src_name : kotenok-malysh-pisklya-6528.jpg
    file_src_name_body : kotenok-malysh-pisklya-6528
    file_src_name_ext : jpg
    file_src_pathname : /tmp/phpy8aOot
    file_src_mime : image/jpeg
    file_src_size : 249605 (max= 2147483648)
    file_src_error : 0
process file to /home/aysen/localhost/phptest/uploads/
- file size OK
- file mime OK : image/jpeg
- new file name body : image_resized
- file name safe format
- destination variables
    file_dst_path : /home/aysen/localhost/phptest/uploads/
    file_dst_name_body : image_resized
    file_dst_name_ext : jpg
- checking for auto_rename
    auto_rename to image_resized_7.jpg
- destination file details
    file_dst_name : image_resized_7.jpg
    file_dst_pathname : /home/aysen/localhost/phptest/uploads/image_resized_7.jpg
- image_resized_7.jpg doesn't exist already
- no image processing wanted
- process OK
is jpg

**Comment by verot** [comment]
> GD version : GD not present
GD is missing on your system; therefore, the class cannot convert the image, and keeps it as JPEG. Which is why you still have the extension .jpg

**Comment by nesyaz** [comment]
Thanks, I got it.
