### ISSUE TITLE
csv saves a txt

### ISSUE THREAD

**Issue by serge512** [verot/class.upload.php#20]
HI i need to upload csv files but when i do i only get a txt file i know it will still work but when i try to delete the file it never does as it doesn't exist as csv but txt.

**Comment by verot** [comment]
You should record the final file name, which you can get by reading `$hande->file_dst_name`after calling `Process()`

**Comment by serge512** [comment]
i'm using $file $p_file->file_dst_name_body . '.' . $p_file->file_dst_name_ext.

and after i do the process i do unset, with full path and name with extencion

**Comment by verot** [comment]
Can you copy here the logs produced by the class?

**Comment by serge512** [comment]
how can i get them i never used it?

**Comment by verot** [comment]
Output `handle->log` after calling `Process()`
