### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by ajan1** [verot/class.upload.php#21]
> Line 2504: PHP 4 constructors are now deprecated
  function upload($file, $lang = 'en_GB')
    {
    }

**Comment by verot** [comment]
I suppose you are using PHP 7? The class will probably not be updated for PHP 7, unless it can be backward compatible with PHP 5 and 4.

**Comment by ajan1** [comment]
Yeah, I tried use it with PHP7. sorry, I forgot said it. 

I think, at change "function upload(" to function "__construct(" is enought for PHP5 and PHP7, but I am not sure.

**Comment by mingtsay** [comment]
FYI: https://wiki.php.net/rfc/remove_php4_constructors
E_DEPRECATED is raised.

**Comment by verot** [comment]
If possible, I would like to keep it backward-compatible with PHP 4, 5 and 7.
But if it is not possible, I am happy to merge a patch with PHP 5 and 7 compatibility, and then we can add a note for PHP 4 users.

**Comment by mmarton** [comment]
How about adding something like this to the class?

```
function  __construct($file, $lang = 'en_GB')  {
    $this->upload($file, $lang);
}
```

works in every version:
php4 will ignore it and use the old version
php5 will prefer the new __construct method
php7 won't show E_DEPRECATED error

**Comment by verot** [comment]
I have pushed a new version (5d95fb237), with the solution you suggested. I tested on PHP 5.3, 5.6 and 7.0, it all works fine without raising errors or warnings. I couldn't test on PHP4, but I expect it to work.

Is it working on your end?

**Comment by mmarton** [comment]
Yes, works fine on php7 for me.
Thanks for the quick change.
