### ISSUE TITLE
Replace instead of autorename 

### ISSUE THREAD

**Issue by VijayaSankarN** [verot/class.upload.php#24]
How can I replace the existing file instead of renaming the file?

**Comment by verot** [comment]
What do you mean?

**Comment by VijayaSankarN** [comment]
I have used 
```
$handle->file_new_name_body = $_GET['pid']; //$_GET['pid']; = 65
```
So I get 65.jpg when I upload an image. When I want to update the image for the same pid 65, when I upload I get 65_1.jpg. But I want the first uploaded image to be replaced instead of renaming. I used this:
```
$handle->file_auto_rename = false;
```
But this time I get error: `Error: 65.jpg already exists. Please change the file name.`

**Comment by verot** [comment]
Check the documentation; you need to use `$handle->file_overwrite`.

You can also check the log produced by the class, it explains everything.

Please refrain to open issues for support queries: issues are for bugs and improvments of the code, not for support.

**Comment by VijayaSankarN** [comment]
Thanks a lot!! Sorry for creating issue instead of raising support. God
Bless You for this wonderful work!!


Vijaya Sankar N.
vijayasankar.me.pn
