### ISSUE TITLE
composer not working proberly

### ISSUE THREAD

**Issue by benzon** [verot/class.upload.php#25]
Hi;
Nice class no doubt! But would be nice if you got it working with the autoloader featured by composer, right now i got to load this manual.

**Comment by verot** [comment]
There is already a `classmap`. You mean PSR-4?  Feel free to sumit a patch, I'll gladly merge it.

**Comment by benzon** [comment]
Right now its just not loading every other class i got is loading with out a issue

```
{
    "autoload": {
        "classmap": ["src/", "lib/", "Something.php"]
    }
}
```

This is the correct classmap and right now you use something like src/Something.php

Think if you just want to load a file insted, you should use.

```
"autoload": {
		"files": ["src/Something.php"]
	}
```

Ill just try it out and give you a heads up on it after i made the changes.
