### ISSUE TITLE
File Type Validation with File Extension

### ISSUE THREAD

**Issue by cyberwani** [verot/class.upload.php#27]
@verot 
Add support for file type validation with file extension.

Currently, I am doing like this.
```php
$file_types = array(
	'doc',
	'docx',
	'txt',
	'xls',
	'xlsx',
	'csv',
	'jpg',
	'jpeg',
	'png'
);
$handle = new Upload($file);
if ($handle->uploaded) {
	$file_types_mime = array();
	foreach( $file_types as $file_type ){
		$file_types_mime[] = $handle->mime_types[$file_type];
	}
	$handle->allowed = $file_types_mime;
}
```

**Comment by verot** [comment]
No, I don't think I will add such a feature, for it is a lot better to use MIMES, and to have a list of MIMES (like `image/*`).

If the feature is really needed, it can be done easily just outside the class, as you are doing.

**Comment by cyberwani** [comment]
Okay
