### ISSUE TITLE
Errors when upgrading to PHP 5.4.3

### ISSUE THREAD

**Issue by b44rd** [verot/class.upload.php#3]
Seems like the class isn't compatible when upgrading to PHP 5.4.3.

**Comment by b44rd** [comment]
The errors seems to come from this regex; preg_match("/^([\.-\w]+)\/([\.-\w]+)(.*)$/i", $this->file_src_mime), which is used several places: 

Warning: preg_match(): Compilation failed: invalid range in character class at offset 7 in /whatever/class.upload.php on line 2871

Warning: preg_match(): Compilation failed: invalid range in character class at offset 7 in /whatever/class.upload.php on line 2911

Warning: preg_match(): Compilation failed: invalid range in character class at offset 7 in /whatever/class.upload.php on line 2938

Warning: preg_match(): Compilation failed: invalid range in character class at offset 7 in /whatever/class.upload.php on line 2965

Warning: preg_match(): Compilation failed: invalid range in character class at offset 7 in /whatever/class.upload.php on line 2983

Warning: preg_match(): Compilation failed: invalid range in character class at offset 7 in /whatever/class.upload.php on line 2871

Warning: preg_match(): Compilation failed: invalid range in character class at offset 7 in /whatever/class.upload.php on line 2911

Warning: preg_match(): Compilation failed: invalid range in character class at offset 7 in /whatever/class.upload.php on line 2938

Warning: preg_match(): Compilation failed: invalid range in character class at offset 7 in /whatever/class.upload.php on line 2965

**Comment by verot** [comment]
Please make sure you are using the tatest version. The preg_match issue has been fixed a long time ago.

**Comment by b44rd** [comment]
Thanks a ton! You are totally right. I had forgotten to update to the latest version. Sorry about this.
