### ISSUE TITLE
Directory removal 

### ISSUE THREAD

**Issue by D0Gmatist** [verot/class.upload.php#30]
I want to suggest to add a parameter, you may be interested
Before you perform
`$Handle->clean();`

2 parameters:
```
$Handle->directory_removal_status = TRUE;
$Handle->directory_removal = '/dir1/dir2/dir3/';
```

For example, we have a file is:
**'Uploads/foto/dir1/dir2/dir3/file.jpg'**

Delete the file:
`$Handle->clean ();`

check:
directory removal and file path to compliance

'**/dir1/dir2/dir3/**' == 'uploads/foto**/dir1/dir2/dir3/**file.jpg'
And remove directory:
**uploads/foto/dir1/dir2/dir3
uploads/foto/dir1/dir2
uploads/foto/dir1**
If the bottom is no other directories and files

**Comment by verot** [comment]
Thank you for the idea. However, I think that is an edge case that is best left out of the class.
