### ISSUE TITLE
preg_replace will be deprecated in php from php 5.5

### ISSUE THREAD

**Issue by Crispijn** [verot/class.upload.php#31]
Hi there,

My webhost is not supporting older versions than 5.6 because of safety issues. The preg_replace function will be deprecated from php 5.5 and on so I can't use this upload class anymore!

It is possible for you to rewrite the upload class to make it compatible with php versions > 5.5? So all the calls for preg_replace need to be reworked to preg_replace_callback.

Looking forward to your reaction.

Regards,

Crispijn, Amsterdam

**Comment by verot** [comment]
` preg_replace` is being deprecated? Only the `/e` modifier is, and is not used in the class.

> As of PHP 5.5.0 E_DEPRECATED level error is emitted when passing in the "\e" modifier. As of PHP 7.0.0 E_WARNING is emited in this case and "\e" modifier has no effect. 

What error do you have?
