### ISSUE TITLE
Save thumb and big

### ISSUE THREAD

**Issue by jenokizm** [verot/class.upload.php#32]
tell me how to best save the downloaded image in two versions: small and big. Now I just call twice to obtain the image, but the process takes a relatively long time.

`function GetImage($s){	
		$handle = new upload($_FILES['image'], 'ru_RU');
		if ($handle->uploaded) {			
			$handle->image_x              = $s;
			$handle->image_y              = $s;
			
			if ($handle->processed) {
				//echo 'image resized';
				return $handle->process();
				$handle->clean();
			} else {
				echo'image error : ' . $handle->error;
			}
		}
	}`
Call:
`$Item["imagethumb"] = GetImage(100);
$Item["imagebig"] = GetImage(1024);`

**Comment by verot** [comment]
This is not a support forum. Please see the code in the test file upload.php, where it explains how to save several images from one same upload.

**Comment by jenokizm** [comment]
rough. yet tested your script came across a error
![perr](https://cloud.githubusercontent.com/assets/11296510/14348984/8df6efe8-fcc8-11e5-9788-d255c7ba9889.PNG)

**Comment by verot** [comment]
It looks to me like your server must be slow, for it doesn't have time to process the image within 30 seconds. Try with a smaller image, it should work.

**Comment by jenokizm** [comment]
no, powerful PC. maybe it's the [Putincize](https://www.youtube.com/watch?v=Fcb4rLzXFl0))
I come as a whole decided my questions. Download Time image in two versions is the same that in my dual method call that sequential process like in your example. no difference. topic is exhausted.
