### ISSUE TITLE
Line number 2324: you missed a slash

### ISSUE THREAD

**Issue by crazysurajit** [verot/class.upload.php#34]
Line number 2324: you missed a slash ('/') in-front of 'extras/magic'
Not sure about other environment but with XAMPP it tries to look for the magic_file in (C:\xampp\phpextras\magic)
So, it prints:
E_WARNING - finfo_open(C:\xampp\phpextras\magic): failed to open stream: No such file or directory in file C:\xampp\htdocs\www\lib\class.upload.php on line 2337

**Comment by verot** [comment]
Any better now? 62bc7ec3b18f2a3eb7eb99e4feca843b2481a41b

**Comment by crazysurajit** [comment]
Absolutely Perfect! and thanks a lot for this awesome library +1:
