### ISSUE TITLE
how to crop image and resize

### ISSUE THREAD

**Issue by aportx** [verot/class.upload.php#37]
--------- To RU
Привет! отличный скрипт!
Подскажи пожалуйста, как решить мою проблему
я использую скрипт http://odyniec.net/projects/imgareaselect/
как использовать параметры которые выдает этот плагин, чтобы сделать кроп картинки с помощью твоего плагина?
какому параметру в Upload() передавать координаты (X1:		Width:	Y1:		Height:	X2:			Y2:) новой картинки?
Заранее спасибо за помощь!
--------- To EN
Hello! a great script !
Please tell me how to solve my problem
I use a script http://odyniec.net/projects/imgareaselect/
how to use the options that gives this plugin to make crop pictures using your plugin ?
what parameter in the Upload() to transmit the coordinates (X1: Width: Y1: Height: X2: Y2 :) a new picture ?
Thank you in advance for your cooperation!

**Comment by verot** [comment]
Please have a look at the documentation.

**Comment by aportx** [comment]
@verot sorry, I not quite understand English, translate Google translator. in documentation a lot of parameters , the names of which the interpreter translates the same way, and I can not understand the difference between them. I thought you could help.

**Comment by verot** [comment]
_image_crop crops image. accepts 4, 2 or 1 values as 'T R B L' or 'TB LR' or 'TBLR'. dimension can be 20, or 20px or 20% (default: null)_

So it is like this: $handle->image_crop = array(**top**,**right**,**bottom**,**left**);

**Comment by aportx** [comment]
@verot Thank you so much. now try to append scripts to each other . and what is meant by "T R B L" - an abbreviation of the full word ? sorry for my English :(

**Comment by verot** [comment]
T R B L = Top Right Bottom Left

**Comment by aportx** [comment]
@verot thank you very much for help ! You really helped . in the plug-in you can not get the width of the original image to calculate the indentation on the right, I had to do a little crutch.
and so everything seems to be working.
