### ISSUE TITLE
Warning: preg_match(): Compilation failed: invalid range in character class at offset 7

### ISSUE THREAD

**Issue by Stephan-UMG** [verot/class.upload.php#38]
Hi verot,

first I would say thank you for your beautiful upload class and your work.

Nowdays, when I use your class I become 5 warnings with the same issue, because of my new PHP Version 5.6.

Warning: preg_match(): Compilation failed: invalid range in character class at offset 7
if (preg_match("/^([\.-\w]+)\/([\.-\w]+)(.*)$/i", $this->file_src_mime)) {

I'm not a "regex-expert", I found on stackoverflow that the dash must be escaped because of the PHP Version 5.6. " **\\-**". Is this correct?

Thanks for your answer and greetings from Berlin,

Max

**Comment by verot** [comment]
Are you using the latest version of the code? This should be fixed.

**Comment by Stephan-UMG** [comment]
I used version 0.32, I downloaded the latest version from here and now it works :-) thanks for your answer
