### ISSUE TITLE
When posting zip file script doesn't work

### ISSUE THREAD

**Issue by aniket27** [verot/class.upload.php#39]
When i try to upload zip file or any file that is above 1.5 mb then the code below this line doesn't execute

```
require ('../library/verot/class.upload.php');
  
   $handle = new upload($_FILES['shareFile']);
   if ($handle->uploaded)
   { echo "script working"; exit;
```

but above example doesn't echo anything what could be the reason because no error is generated in the php

**Comment by verot** [comment]
You are probably running out of memory. Check for errors in your web server.
