### ISSUE TITLE
Upload from URL

### ISSUE THREAD

**Issue by sinan4yildiz** [verot/class.upload.php#40]
Is it possible to upload from url?

**Comment by verot** [comment]
This is better done outside the scope of the class, and then using the class on the local file you retrieved.
See these threads: [1](http://www.verot.net/php_class_upload_forum.htm?php_class_upload_forum_thread_id=1167)  and [2](http://www.verot.net/php_class_upload_forum.htm?php_class_upload_forum_thread_id=4617)
