### ISSUE TITLE
Text Size and Text Position 

### ISSUE THREAD

**Issue by bado57** [verot/class.upload.php#41]
Hi verot many thanks.
 Your script file text size max 5, but I think very small. How to grow it. 
Second question ; [http://phpimageworkshop.com/tutorial/1/adding-watermark.html](url)

 This sample  text size larger and text position cross or flat, but your example, I can not do it cross position, TOP-RİGHT/CROSS.
 
Another situation, writing on watermark. 
Please help me. God chance.

**Comment by verot** [comment]
The class uses GB built-in fonts (from 1 to 5, 1 being the smallest). You cannot change the size, you can just select a font via _image_text_font_

Note that you can also use your own fonts, as long as they are converted to GDF fonts. In that case, you can tweak the size as you see fit, and provide the path to the GD font in _image_text_font_.

**Comment by verot** [comment]
As for the watermark, you cannot do "top-right/cross" with the class. You cannot also write on the watermark, although if you work out the positions, you can do it with _image_text_position_, _image_text_x_, _image_text_y_, and image_watermark_position_, _image_watermark_x_ and _image_watermark_y_.

Maybe, the best solution would be to prepare an watermark as an image, wit hthe text in a diagonal, and with the font you want.
