### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by eddpuika** [verot/class.upload.php#42]
Soo my problem is this - i was using version .33dev and all worked fine except i run into image orientation problem, soo i looked for posible solutions and found that version .33 has built in image_auto_rotate soo i was really happy, but when i`m using the new version i`m runing into the problem, that wasnt before - if i upload big images ~4Mb i have fattal error: Allowed memory size exhausted, i have post limit 64Mb, file upload limit 30Mb  and memory limit 128Mb, soo im baffled what is wrong. Can you please help me?

**Comment by verot** [comment]
Probably the rotation feature is using the memory you have left for a given image. Does the file process if you set `image_auto_rotate` to `false`? If yes, then it means that you will need to increase available memory so that the rotation can happen.
