### ISSUE TITLE
MIME types for office documents now working

### ISSUE THREAD

**Issue by McCuz** [verot/class.upload.php#43]
I've been trying to upload some excel files and I've set up mime types like this:
` $handle->allowed = array('application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.spreadsheetml.template', 'application/vnd.ms-excel.sheet.binary.macroEnabled.12', 'application/vnd.ms-excel.addin.macroEnabled.12');`

Using all the excel mime types I've found, but I still get "Incorrect type of file" on every .xlsx file while .xls uploads without a problem.

(Same problem with .docx, .pptx)

When I try to get file mime type with ->file_src_mime i get either "application/zip" or "application/x-empty"

**Comment by verot** [comment]
Can you send me one of these Excel file?

**Comment by McCuz** [comment]
http://datoteke.demetra-leanway.com/?KopijaPSB.xlsx

**Comment by verot** [comment]
The MIME for this file is _application/vnd.openxmlformats-officedocument.spreadsheetml.sheet_, which is supported by the class.

Can you copy/paste here the log as produced by the class? It will tell you which method it uses to check the MIME
