### ISSUE TITLE
Not Doc example support for UTF-8 text and TTF fonts

### ISSUE THREAD

**Issue by EOM** [verot/class.upload.php#44]
Hi, no doc example support for UTF-8 text and TTF fonts..?

**Comment by verot** [comment]
There is no support yet for TTF fonts and UTF-8 text. So far, the class can only use GD fonts. You can still create a GDF font with the characters that you want, but it is a bit overkill.

I have planned to implement TTF fonts in the class, but haven't yet found the time to do it.

**Comment by EOM** [comment]
Hello,
But sources * .GDF are not simple to get in addition to having to make a .TTF processes * a * .GDF.

It is simpler to add a method that supports
http://php.net/manual/en/function.imagettftext.php

Example:
// Img
$im = imagecreatetruecolor(400, 30);
// Create some colors
$grey = imagecolorallocate($im, 128, 128, 128);
// The text to draw
$text = 'Testing...';
// Replace path by your own font path
$font = 'arial.ttf';
// Add some shadow to the text
imagettftext($im, 20, 0, 11, 21, $grey, $font, $text);

**Comment by verot** [comment]
I am aware of _imagettftext_ and even have some rough implementation laying around somewhere. I just didn't find the time as of yet to make it production-ready.

**Comment by EOM** [comment]
My solution Temp is easy:

```
                   $UploadImg = new upload(.......);
                    ....
                    ....
                   // Get Img upload
                    $im = imagecreatefromstring ($UploadImg->upload->Process());

                    $color1 = imagecolorallocate($im, 0, 0, 0);
                    $font = WWW_ROOT."files/fonts/DancingScript-Regular.ttf";

                   // Set text
                    $text1 = 'Hola Mundo';
                    imagettftext($im, 48, 0, 580, 180, $color1, $font, $text2);

                    $text2 = 'Text 2 Demo Test OK.... ;-)';
                    imagettftext($im, 48, 0, 30, 280, $color1, $font, $text1);

                    header('Content-type: ' . $UploadImg->upload->file_src_mime);
                    imagejpeg($im);
                    imagedestroy($im);
                    die();
```

**Comment by verot** [comment]
I have added experimental support for UTF-8 and TrueType fonts, in f5a3ce97bfe61d28183be35bf167f6f3e76c0728

Would you mind trying it?
