### ISSUE TITLE
Chnage The Name of File Uploaded On Class.upload.php

### ISSUE THREAD

**Issue by Yukusawa** [verot/class.upload.php#46]
Hiii , 
First , I would Thank you For the Great Class :+1: , Second , I want To know Ho to change The name Of the File , I won't To fix the first name . and I want to change _1 I won't it ... Please Excuse me And Thank u Again

**Comment by verot** [comment]
I am not sure what you mean. 

But you should look for `file_new_name_body`, `file_name_body_add`, `file_name_body_pre`, and `file_overwrite`
