### ISSUE TITLE
Require dev-master

### ISSUE THREAD

**Issue by braghimsistemas** [verot/class.upload.php#47]
Firstly we want to congrats you for this awesome feature.
I personally have used this class for a long years ago. Thank you.

Hello, we use this class in our project [SuitUp PHP Framework](https://github.com/braghimsistemas/suitup-php).
We got an error while try to install dependencies with composer when it is in `dev-master`. The point is that you recommend us to use as dev-master.

So, do have too much difference between dev-master and 0.33 release?

**Comment by verot** [comment]
What error do you have? `dev-master` is ahead of `0.33`, and has new features. But you can use `0.33`, it works well.

**Comment by braghimsistemas** [comment]
The error is that dependencies conflicts, even having nothing to conflict, weird error.
Well, we point to the 0.33 release and watch till you release another one ;)

Thanks a lot for your answer.
