### ISSUE TITLE
Cannot End Filename In Variable

### ISSUE THREAD

**Issue by Jongosi** [verot/class.upload.php#48]
This issue occurs when you try to save a filename **ending** in a variable.

The following does not work:

    $handle->file_new_name_body = "img_{$var}";

But this _does_ work:

    $handle->file_new_name_body = "img_{$var}_"; // <-- note the underscore

In the first instance, the class tries to rename the filename by appending an integer suffix; `_1`, `_2` and so on, between the supplied filename and the file extension. In the above example, if the value of **$var = 'test';** the resulting filename will be **img_test_1.jpg**

If I set the option:

    $handle->file_auto_rename = false;

then the file is not saved at all.

**Comment by verot** [comment]
I don't understand what you mean.  

This:
 ```php
$var = 'test';
$handle->file_new_name_body = "img_{$var}";
```
Is the same as this:
 ```php
$handle->file_new_name_body = "img_test";
```

So the fact that there is a variable interpolation doesn't matter.

And then, if you have:
 ```php
$handle->file_new_name_body = "img_test";
```
You get as images:
 ```php
img_test.jpg
img_test_1.jpg
img_test_2.jpg...
```

Or, if you have:
 ```php
$handle->file_new_name_body = "img_test_";
```
You get as images:
 ```php
img_test_.jpg
img_test__1.jpg
img_test__2.jpg...
```

I don't see where the problem is...

**Comment by Jongosi** [comment]
I never get an upload named:

`img_test.jpg`

It's always `img_test_1.jpg` then subsequently `img_test_2.jpg`, then `img_test_3.jpg` and so on.

Additionally, if I set 

`$handle->file_auto_rename = false;`

Then nothing is saved at all.

> Thanks for an awesome class by the way, and all your hard work!

**Comment by verot** [comment]
Can you copy here the logs produced by the class for each of your attempts you are describing above?

**Comment by Jongosi** [comment]
I just got this to work by removing the call to `$handle->clean();`:

    $handle = new upload( $filePath );

    if ( $handle->uploaded ) {
        // main image

        $handle->file_new_name_body = (string) $pathMain;
        $handle->allowed            = array('image/*');
        $handle->image_resize       = true;
        $handle->image_no_enlarging = true;
        $handle->jpeg_quality       = 50;
        $handle->image_x            = 512;
        $handle->image_y            = 288;
        $handle->file_overwrite     = true;
        $handle->file_auto_rename   = false;
        $handle->process( $imgPath );

        if ( !$handle->processed ) {
            $errors[] = $handle->error;
        }

        // thumb

        $handle->file_new_name_body = (string) $pathThumb;
        $handle->allowed            = array('image/*');
        $handle->image_resize       = true;
        $handle->image_no_enlarging = true;
        $handle->jpeg_quality       = 50;
        $handle->image_x            = 192;
        $handle->image_y            = 108;
        $handle->file_overwrite     = true;
        $handle->file_auto_rename   = false;
        $handle->process( $imgPath );

        if ( !$handle->processed ) {
            $errors[] = $handle->error;
        }

        $handle->clean(); // <-- removed this and filenames are working now
    }

**Comment by verot** [comment]
This shouldn't have an effect. Can you copy here the logs produced by the class, with and without  `$handle->clean()`?

**Comment by Jongosi** [comment]
Can you tell me how to get the log contents? I can't see anything in the docs about logging? Thanks.

**Comment by verot** [comment]
Just add this at the end of your code: `echo $handle->log;`

**Comment by danman12345** [comment]
I got the same problem. $handle-> clean(); solved the problem
