### ISSUE TITLE
PCRE issue?

### ISSUE THREAD

**Issue by noraheuer** [verot/class.upload.php#5]
recently upgraded MAMP (v 3.3) using php v 5.4.42

PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 7 in .../class.upload_0.32.php on line 2899
PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 7 in .../class.upload_0.32.php on line 2939
PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 7 in .../class.upload_0.32.php on line 2966
PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 7 in .../class.upload_0.32.php on line 2993
PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 7 in .../class.upload_0.32.php on line 3011

escaping the hyphens should fix this.

example from line #2899

- if (preg_match("/^([\.-\w]+)\/([\.-\w]+)(.*)$/i", $this->file_src_mime)) {
+ if (preg_match("/^([\.\-\w]+)\/([\.\-\w]+)(.*)$/i", $this->file_src_mime)) {

**Comment by verot** [comment]
Please use the laster version (master), this has been fixed.

**Comment by noraheuer** [comment]
Sorry I should have said. I'm using version 0.32 - is that not the latest version?

**Comment by noraheuer** [comment]
never mind. downloading the master fixed it.
