### ISSUE TITLE
Animated gifs stopped working in latest version

### ISSUE THREAD

**Issue by Mad182** [verot/class.upload.php#50]
Hello!

There seems to be a problem with animated gifs on latest version **0.34dev**.
When I'm uploading animated gifs, it converts them to static images keeping only the first frame after processing, even when mage_resize is set to false and no other manipulations are set.

Animated gifs are working fine on version  **0.33dev** and older.

My settings:

    $upload = new Upload($_FILES['new-image']);
    $upload->file_overwrite = true;
    $upload->file_auto_rename = false;
    $upload->mime_check = true;
    $upload->no_script = true;
    $upload->file_max_size = '20M';
    $upload->allowed = ['image/*'];
    $upload->image_resize = false;

PHP version: 7.0.11

It happens with any animated gif image I tried, e.g. https://gif-avatars.com/img/150x150/happy-cat.gif

**Comment by verot** [comment]
Yes, there is a bug. Not that easy to fix. In the meantime, you can comment out line 3131
https://github.com/verot/class.upload.php/blob/master/src/class.upload.php#L3131

**Comment by verot** [comment]
I pushed a fix on `master`, it should be fine now.

**Comment by Mad182** [comment]
Works fine for me, thank you!

**Comment by Mad182** [comment]
Last commit broke animated GIF support again.

Looks like getsize now returns 0 when it should return null.

It can be fixed by adding 

```
if($size === null) {
	return null;
}
```

to the start of getsize()

**Comment by verot** [comment]
Thanks.Fixed in b983e88

**Comment by day83** [comment]
Still cannot resize an animated gif.

**Comment by romanzipp** [comment]
When uploading animated GIFs with the following settings, the processed .gif ist not animated anymore.

**Settings:**
```php
$handle = new upload($_FILES['image']);
$handle->allowed = ['image/gif', 'image/jpg', 'image/jpeg', 'image/png'];
if ($handle->uploaded) {
    if ($handle->file_src_mime == 'image/gif') {
        $upload->image_resize = false;
    }
    // Some more stuff for jpg, png etc.
    $handle->file_name_body_pre = 'post_';
    $handle->file_new_name_body = time().'-'.Random::string(32);

    $handle->process(__DIR__.'/../../public/images/');
}
```

**Comment by seba1rx** [comment]
I can resize an animated GIF but it loses animation, 
I appreciate all the work but still, will this be ever fixed?

**Comment by verot** [comment]
Structurally speaking, the class cannot deal with animated GIFs. I can maybe detect the animated GIFs, but the class cannot apply graphic manipulation on each layer of the animated GIF.

So as it stands, the class can only upload animated GIFs as regular files, or do graphic processing on the GIF image, but removing the animation.

There is no plan to support animated GIFs in the class.

**Comment by seba1rx** [comment]
For now I'm unreliably detecting the mime type and detecting if it is gif, if so, not to resize.

What about doing something like this:
[Resize animated GIF file without destroying animation](https://stackoverflow.com/questions/718491/resize-animated-gif-file-without-destroying-animation)
