### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by leventmenekse** [verot/class.upload.php#52]
Can you add namespace ?

**Comment by verot** [comment]
I have chosen not to add namespaces, so that the class can remain backward compatible with PHP4 and 5. 

But maybe you can suggest a solution so that the class can be namespaced, yet compatible with older versions of PHP?

**Comment by leventmenekse** [comment]
I don't know a way to support older PHP version with namespace actually. I like this library, my only concern is that if i want to use another class named upload then it conflicts.

**Comment by ApuRed** [comment]
Yes, I spent years using its application was always the best on the market for my taste, full, but now need to use laravel and I would love to have a namespace or somehow use it with laravel

**Comment by verot** [comment]
Honestly, I have no time now to research the issue right now. But if you provide me with a patch or create a pull request, I will merge it, so we'll have namespaces. People using PHP <5.3 will remain at current version, or I will do a separate branch for backward compatibility.

**Comment by rickerd** [comment]
Maybe use versions/releases instead all on dev-master.
This way you can let other lower versions to still work.

**Comment by marcosfreitas** [comment]
Improve the versioning rules is the solution if you want to support older versions of PHP.

**Comment by verot** [comment]
Class is now namespaced since version 0.36
