### ISSUE TITLE
Function orientation (portrait | landscape | square)

### ISSUE THREAD

**Issue by satrianivzla** [verot/class.upload.php#54]
Hi There
is possible to add some kind of function that bring image orientation as a basic info ?
thank you

**Comment by verot** [comment]
You mean when it displays _source file is an image_, and provides the original image sizes, etc... you would like it to state the image orientation?

You can get it easily, with _image_src_x_ and _image_src_y_, can't you?

Anyway, the problem is that at this stage (before calling `process()`, the EXIF auto-orientation hasn't been checked yet. So it will not be very useful...

**Comment by satrianivzla** [comment]
Yes I understand your point and I am trying to find the best solution but the main goal that I am looking for is know the image orientation to later have the option to be able to ordered by orientation and make it more graphically and esthetic.
I already done that in the past and I am just trying to do it again using your class.

**Comment by verot** [comment]
It is tricky. Basically, whe nyou instantiate the upload, the class retrieves _image_src_x_ and _image_src_y_. These are the real dimensions of the image file. From these, you can easily get the orientation.
Now, the EXIF auto-orientation happens later, in `process()`. There, before doing image manipulations, it checks whether the image has to be flipped or rotated according to EXIF data.

So what would need to be done is the following:
* Do the EXIF auto-orientation check in the constructor
* Store _image_src_x_ and _image_src_y_ as _image_real_x_ and _image_real_y_ to hold the actual file image dimensions
* Provide _image_src_x_ and _image_src_y_, but taking into account the EXIF orientation
* Provide _image_orientation_ as a helper to indicate if the image is square, portrait or landscape
* Then, in `Process()`, use _image_src_x_ and _image_src_y_ to check on image dimensions
* But use _image_real_x_ and _image_real_y_ as the source image dimensions, and flip/rotate the image of needed
* One the image is flipped/rotated, use _image_src_x_ and _image_src_y_ to carry on

It is quite a bit of work, and I am afraid I have little time right now. But I will do it at some point.

**Comment by Mouradlayouni** [comment]
Hi there,
The EXIF auto-orientation doesn't work fine.

**Comment by verot** [comment]
What do you mean? Can you provide a test case?

**Comment by Mouradlayouni** [comment]
When I tried to upload an image with orientation 90 (EXIF orientation = 6), an error "Maximum execution time of 30 seconds exceeded " appeared.

**Comment by verot** [comment]
Do you have the issue with this image? https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_6.jpg

**Comment by Mouradlayouni** [comment]
Yes. And the dimensions of my image are 2300px / 4100px and the size is 2.4 MB.

**Comment by verot** [comment]
So the image above (Landscape_6.jpg) results in a PHP timeout? 

As for your image, it is large, and rotation is quite costly in terms of CPU and memory...

**Comment by Mouradlayouni** [comment]
Yes.
