### ISSUE TITLE
why $handle->image_convert = 'png' not work

### ISSUE THREAD

**Issue by iFunbox** [verot/class.upload.php#55]
why $handle->image_convert = 'png' not work
img upload success,but jpg not convert png
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mhash
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by verot** [comment]
You need to copy here the log produced by the class.

**Comment by fanhefan** [comment]
system information
- class version : 0.34dev
- operating system : Linux
- PHP version : 5.6.19
- GD version : 2.1.0
- supported image types : png gif bmp
- open_basedir : no restriction
- upload_max_filesize : 50M (52428800 bytes)
- language : en_GB
source is an uploaded file
- upload OK
- file name OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    MAGIC path will not be used
    MIME type detected as image/jpeg; charset=binary by Fileinfo PECL extension
- MIME validated as image/jpeg
source variables
- You can use all these before calling process()
    file_src_name : 9E349346E617072206223652B5C0D3B5.jpg
    file_src_name_body : 9E349346E617072206223652B5C0D3B5
    file_src_name_ext : jpg
    file_src_pathname : /tmp/phpHTXni6
    file_src_mime : image/jpeg
    file_src_size : 51143 (max= 52428800)
    file_src_error : 0
process file to ../demand/public/upload/stuff/img/201611/
- file size OK
- file mime OK : image/jpeg
- new file name body : 70c4904b9b065d7d2a574cfd88ce6b96
- file name safe format
- destination variables
    file_dst_path : ../demand/public/upload/stuff/img/201611/
    file_dst_name_body : 70c4904b9b065d7d2a574cfd88ce6b96
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : 70c4904b9b065d7d2a574cfd88ce6b96.jpg
    file_dst_pathname : ../demand/public/upload/stuff/img/201611/70c4904b9b065d7d2a574cfd88ce6b96.jpg
- 70c4904b9b065d7d2a574cfd88ce6b96.jpg doesn't exist already
- auto-rotate applies only to JPEG images
- no image processing wanted
- process OK

**Comment by verot** [comment]
Can you copy here your code which calls the class?

**Comment by fanhefan** [comment]
```
$this->load->library('MyNewUpload',$_FILES['img']);
		$handle = $this->mynewupload;
		if ($handle->uploaded) {
			$handle->allowed = array('image/*');
			$handle->file_new_name_body = md5($_FILES['img']['name'] . uniqid());
			$handle->image_convert = 'png';
			$handle->process(FCPATH.'public/upload/' . $path . '/img/' . date('Ym'));
			if ($handle->processed) {

				$path = str_replace(FCPATH.'public/upload', '', $handle->file_dst_pathname);
				$img_url = PIC_URL.$path;
				$info = array('status' => 0, 'data'=> array('img_url' => $img_url));
				echo json_encode($info);
				exit;
			}
		}
		$info = array('status' => 1, 'data'=> array(), 'error'=>$handle->error);
		echo json_encode($info);
		exit;
```

**Comment by verot** [comment]
You code is OK. I think you have a server issue. Your GD version is 2.1.0, which is OK (but it is not the latest version). However, your system doesn't support JPEG processing, so your GD cannot handle JPEG. 

In the log, you should see something like this:
```
- GD version              : 2.2.3
- supported image types   : png jpg gif bmp
```

**Comment by fanhefan** [comment]
@verot thanks，i will check
