### ISSUE TITLE
IOS direct upload orientation?

### ISSUE THREAD

**Issue by wbroeke** [verot/class.upload.php#56]
Still having trouble with pictures shot on IOS10 with iPhone6 in portrait mode. After upload without first editing photo shows up as landscape. Should this be working properly in latest release?

**Comment by verot** [comment]
Can you provide a link to the image, as well as your code and the log produced by the class?

**Comment by wbroeke** [comment]
But should this be working? Just to be sure not to bother you before checkong my own code

**Comment by verot** [comment]
Yes, it should be working, but there may be a bug... So it is worth checking.

**Comment by wbroeke** [comment]
Ok, I'll get back to you then

**Comment by wbroeke** [comment]
I don't know how to output log produced bij the class... 

I can provide you with my code calling your class mostly based off your example scripts.  Any idea if i am doing something wrong here? 
`include('classes/class.upload.php');
// | Copyright (c) Colin Verot 2003-2014. All rights reserved.              |
// | Email         colin@verot.net                                          |
// | Web           http://www.verot.net    
$watermerk = true;                                 
$watermerktekst = "GEKKOSS - " . date("Y");



// Initiate the upload object based on the uploaded file field
$handle = new upload($_FILES['mijnbestand']);

// Only proceed if the file has been uploaded
if($handle->uploaded) {
	
  	$handle->file_new_name_body  = $_POST["sid"] . "_" .  date("Ymd") ."_" . $handle->file_src_name_body;
	$handle->image_no_enlarging = true;
    // Make sure the image is resized
    if ($handle->image_src_x >= 800) {
			$handle->image_resize         = true;
		} else {
			$handle->image_resize         = false;
	}
    $handle->image_x              = 800;
    // Ensure the height of the image is calculated based on ratio
    $handle->image_ratio_y        = true;
    // Process the image resize and save the uploaded file to the directory
	
	if ($watermerk == true) {
		
		$handle->image_text_x = 20;
		$handle->image_text_y = 20;
			$handle->image_text_font = 2;
			$handle->image_text = $watermerktekst;
			$handle->image_text_opacity = 30;
	}
	$handle->jpeg_quality = 100;
    $handle->process($uploadmap);
    // Proceed if image processing completed sucessfully
	
	
	
    if($handle->processed) {
			// Your image has been resized and saved
			if ($_POST["sid"]) {
		
		$safe_sid = htmlspecialchars($_POST["sid"]);
		echo ($safe_sid);

			$sql = "INSERT INTO `fotos` (`subjectid`, `naam`) VALUES ('". $safe_sid."', '".$handle->file_dst_name ."')";
			$resultgetit = mysql_query($sql);
		echo $sql;
	}	
		
        echo 'image resized';
        // Reset the properties of the upload object
        $handle->clean();
    }else{
        // Write the error to the screen
        echo 'error : ' . $handle->error;
    }
}`

**Comment by verot** [comment]
To output the log, print $handle->log at the end

**Comment by wbroeke** [comment]
![20161019_084337017_ios](https://cloud.githubusercontent.com/assets/23261027/20057910/78d4ede4-a4ee-11e6-97c0-5c7a9ea8bdda.jpg)

and a picture example

**Comment by wbroeke** [comment]
from local server and upload via PC

image resizedsystem information
- class version : 0.34dev
- operating system : WINNT
- PHP version : 5.6.12
- GD version : 2.1.0
- supported image types : png jpg gif bmp
- open_basedir : no restriction
- upload_max_filesize : 8M (8388608 bytes)
- language : en_GB
source is an uploaded file
- upload OK
- file name OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    Fileinfo PECL extension not available
- Checking MIME type with UNIX file() command
    UNIX file() command not availabled
- Checking MIME type with mime.magic file (mime_content_type())
    mime_content_type() is not available
- Checking MIME type with getimagesize()
    MIME type detected as image/jpeg by PHP getimagesize() function
- MIME validated as image/jpeg
source variables
- You can use all these before calling process()
    file_src_name : 20161019_084337017_iOS.jpg
    file_src_name_body : 20161019_084337017_iOS
    file_src_name_ext : jpg
    file_src_pathname : C:\xampp2\tmp\php4907.tmp
    file_src_mime : image/jpeg
    file_src_size : 2281962 (max= 8388608)
    file_src_error : 0
- source file is an image
    image_src_x : 3264
    image_src_y : 2448
    image_src_pixels : 7990272
    image_src_type : jpg
    image_src_bits : 8
process file to images/\
- file size OK
- file mime OK : image/jpeg
- new file name body : 43_20161107_20161019_084337017_iOS
- file name safe format
- destination variables
    file_dst_path : images/\
    file_dst_name_body : 43_20161107_20161019_084337017_iOS
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : 43_20161107_20161019_084337017_iOS.jpg
    file_dst_pathname : images/\43_20161107_20161019_084337017_iOS.jpg
- 43_20161107_20161019_084337017_iOS.jpg doesn't exist already
- EXIF orientation = 6 : 90 rotate right
- image resizing or conversion wanted
- source image is JPEG
- setting destination file type to jpg
- auto-rotate image : 90
- resizing...
    calculate y size
    image_src_x y : 2448 x 3264
    image_dst_x y : 800 x 1067
    resized image object created
- add text
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK
cleanup
- delete temp file C:\xampp2\tmp\php4907.tmp

**Comment by wbroeke** [comment]
image shows right side up!

**Comment by wbroeke** [comment]
this is what the scritps produces when uploading directly from IOS10 phone. Resulting in picture in landscape mode (which is wrong).

`image resizedsystem information
- class version : 0.34dev
- operating system : Linux
- PHP version : 5.5.33
- GD version : 2.1.0
- supported image types : png jpg gif bmp
- open_basedir : /home/medeklinke/:/tmp:/usr/local/lib/php/
- upload_max_filesize : 64M (67108864 bytes)
- language : en_GB
source is an uploaded file
- upload OK
- file name OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    MAGIC path will not be used
    MIME type detected as image/jpeg; charset=binary by Fileinfo PECL extension
- MIME validated as image/jpeg
source variables
- You can use all these before calling process()
    file_src_name : IMG_3909.JPG
    file_src_name_body : IMG_3909
    file_src_name_ext : jpg
    file_src_pathname : /tmp/php3Ubeq7
    file_src_mime : image/jpeg
    file_src_size : 2281962 (max= 67108864)
    file_src_error : 0
- source file is an image
    image_src_x : 3264
    image_src_y : 2448
    image_src_pixels : 7990272
    image_src_type : jpg
    image_src_bits : 8
process file to images/
- file size OK
- file mime OK : image/jpeg
- new file name body : 40_20161107_IMG_3909
- file name safe format
- destination variables
    file_dst_path : images/
    file_dst_name_body : 40_20161107_IMG_3909
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : 40_20161107_IMG_3909.jpg
    file_dst_pathname : images/40_20161107_IMG_3909.jpg
- 40_20161107_IMG_3909.jpg doesn't exist already
- auto-rotate requires function exif_read_data to be enabled
- image resizing or conversion wanted
- source image is JPEG
- setting destination file type to jpg
- resizing...
    calculate y size
    image_src_x y : 3264 x 2448
    image_dst_x y : 800 x 600
    resized image object created
- add text
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK
cleanup
- delete temp file /tmp/php3Ubeq7`

**Comment by wbroeke** [comment]
well that clears up some questions...
**auto-rotate requires function exif_read_data to be enabled**

**Comment by verot** [comment]
_auto-rotate requires function exif_read_data to be enabled_

The function _exif_read_data_ must be enabled on your server. It is on your local machine, but not on your server.

**Comment by wbroeke** [comment]
Yes, that must be it. Had I know how to print the log I would have caught this one myself. Thanks for your time and the great library.

greetings,
Wouter

**Comment by verot** [comment]
No worries. Closing for now.
