### ISSUE TITLE
A non well formed numeric value encountered in...

### ISSUE THREAD

**Issue by CNK001** [verot/class.upload.php#62]
I use this code: https://www.verot.net/php_class_upload_forum.htm?php_class_upload_forum_thread_id=4617 to upload file from url, all works well, but in server logs I have errors like this:
`[Wed Jan 04 13:49:59.888705 2017] [fcgid:warn] [pid 30490:tid 139711553021696] [client 79.187.5.129:54907] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/domains/mydomain/public_html/scripts/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7`

class.upload.php, 2720 line is: 
`                $size *= 1024;`

How can I solve this problem?

**Comment by verot** [comment]
Can you copy here the log produced by the class?

**Comment by CNK001** [comment]
`[Wed Jan 04 13:38:47.312381 2017] [fcgid:warn] [pid 1062:tid 139711469094656] [client 79.187.5.129:54778] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:38:53.246299 2017] [fcgid:warn] [pid 1062:tid 139711720875776] [client 79.187.5.129:54779] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:38:53.246323 2017] [fcgid:warn] [pid 1062:tid 139711720875776] [client 79.187.5.129:54779] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:38:53.246326 2017] [fcgid:warn] [pid 1062:tid 139711720875776] [client 79.187.5.129:54779] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:38:53.246329 2017] [fcgid:warn] [pid 1062:tid 139711720875776] [client 79.187.5.129:54779] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:38:53.246339 2017] [fcgid:warn] [pid 1062:tid 139711720875776] [client 79.187.5.129:54779] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:43:33.202598 2017] [fcgid:warn] [pid 1062:tid 139711804802816] [client 79.187.5.129:54837] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:43:33.202614 2017] [fcgid:warn] [pid 1062:tid 139711804802816] [client 79.187.5.129:54837] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:43:33.202617 2017] [fcgid:warn] [pid 1062:tid 139711804802816] [client 79.187.5.129:54837] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:43:33.202620 2017] [fcgid:warn] [pid 1062:tid 139711804802816] [client 79.187.5.129:54837] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:43:33.202623 2017] [fcgid:warn] [pid 1062:tid 139711804802816] [client 79.187.5.129:54837] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:49:15.749752 2017] [fcgid:warn] [pid 30490:tid 139711737661184] [client 79.187.5.129:54900] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:49:15.749773 2017] [fcgid:warn] [pid 30490:tid 139711737661184] [client 79.187.5.129:54900] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:49:15.749776 2017] [fcgid:warn] [pid 30490:tid 139711737661184] [client 79.187.5.129:54900] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:49:15.749779 2017] [fcgid:warn] [pid 30490:tid 139711737661184] [client 79.187.5.129:54900] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:49:15.749782 2017] [fcgid:warn] [pid 30490:tid 139711737661184] [client 79.187.5.129:54900] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:49:59.888675 2017] [fcgid:warn] [pid 30490:tid 139711553021696] [client 79.187.5.129:54907] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:49:59.888696 2017] [fcgid:warn] [pid 30490:tid 139711553021696] [client 79.187.5.129:54907] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:49:59.888700 2017] [fcgid:warn] [pid 30490:tid 139711553021696] [client 79.187.5.129:54907] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:49:59.888702 2017] [fcgid:warn] [pid 30490:tid 139711553021696] [client 79.187.5.129:54907] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7
[Wed Jan 04 13:49:59.888705 2017] [fcgid:warn] [pid 30490:tid 139711553021696] [client 79.187.5.129:54907] mod_fcgid: stderr: PHP Notice:  A non well formed numeric value encountered in /home/vwtech/domains/mydomain/public_html/skrypty/class.upload.php on line 2720, referer: http://mydomain/administrator/index.php?go=edit_page&id=7`

**Comment by verot** [comment]
I mean the log produced by the class itself, not the web server logs.

**Comment by CNK001** [comment]
Ok, I'm sorry for my mistake. Logs from upload class:

> system information
- class version : 0.34dev
- operating system : Linux
- PHP version : 7.1.0
- GD version : 2.1.0
- supported image types : png jpg gif bmp
- open_basedir : no restriction
- upload_max_filesize : 128M (134217728 bytes)
- language : en_GB
source is a local file /home/site/domains/mydomain/public_html/images/tmp/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- local file OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    MAGIC path will not be used
    MIME type detected as image/jpeg; charset=binary by Fileinfo PECL extension
- MIME validated as image/jpeg
source variables
- You can use all these before calling process()
    file_src_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_src_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_src_name_ext : jpg
    file_src_pathname : /home/site/domains/mydomain/public_html/images/tmp/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_src_mime : image/jpeg
    file_src_size : 118252 (max= 134217728)
    file_src_error : 0
- source file is an image
    image_src_x : 1280
    image_src_y : 720
    image_src_pixels : 921600
    image_src_type : jpg
    image_src_bits : 8
process file to /home/site/domains/mydomain/public_html/images/full/
- file size OK
- file mime OK : image/jpeg
- file name safe format
- destination variables
    file_dst_path : /home/site/domains/mydomain/public_html/images/full/
    file_dst_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_dst_pathname : /home/site/domains/mydomain/public_html/images/full/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg doesn't exist already
- EXIF data is invalid or missing
- no image processing wanted
- process OK

zdjęcie 2000 zostało utworzone i zapisane na serwerze
system information
- class version : 0.34dev
- operating system : Linux
- PHP version : 7.1.0
- GD version : 2.1.0
- supported image types : png jpg gif bmp
- open_basedir : no restriction
- upload_max_filesize : 128M (134217728 bytes)
- language : en_GB
source is a local file /home/site/domains/mydomain/public_html/images/tmp/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- local file OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    MAGIC path will not be used
    MIME type detected as image/jpeg; charset=binary by Fileinfo PECL extension
- MIME validated as image/jpeg
source variables
- You can use all these before calling process()
    file_src_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_src_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_src_name_ext : jpg
    file_src_pathname : /home/site/domains/mydomain/public_html/images/tmp/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_src_mime : image/jpeg
    file_src_size : 118252 (max= 134217728)
    file_src_error : 0
- source file is an image
    image_src_x : 1280
    image_src_y : 720
    image_src_pixels : 921600
    image_src_type : jpg
    image_src_bits : 8
process file to /home/site/domains/mydomain/public_html/images/full/
- file size OK
- file mime OK : image/jpeg
- file name safe format
- destination variables
    file_dst_path : /home/site/domains/mydomain/public_html/images/full/
    file_dst_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_dst_pathname : /home/site/domains/mydomain/public_html/images/full/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg doesn't exist already
- EXIF data is invalid or missing
- no image processing wanted
- process OK
process file to /home/site/domains/mydomain/public_html/images/
- file size OK
- file mime OK : image/jpeg
- file name safe format
- destination variables
    file_dst_path : /home/site/domains/mydomain/public_html/images/
    file_dst_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_dst_pathname : /home/site/domains/mydomain/public_html/images/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg doesn't exist already
- EXIF data is invalid or missing
- image resizing or conversion wanted
- source image is JPEG
- setting destination file type to jpg
- resizing...
    calculate y size
    image_src_x y : 1280 x 720
    image_dst_x y : 2000 x 1125
    cancel resizing, as it would enlarge the image!
- add watermark
    watermark source image is PNG
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK

miniaturka zdjęcia 140p została utworzona i zapisana na serwerze
system information
- class version : 0.34dev
- operating system : Linux
- PHP version : 7.1.0
- GD version : 2.1.0
- supported image types : png jpg gif bmp
- open_basedir : no restriction
- upload_max_filesize : 128M (134217728 bytes)
- language : en_GB
source is a local file /home/site/domains/mydomain/public_html/images/tmp/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- local file OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    MAGIC path will not be used
    MIME type detected as image/jpeg; charset=binary by Fileinfo PECL extension
- MIME validated as image/jpeg
source variables
- You can use all these before calling process()
    file_src_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_src_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_src_name_ext : jpg
    file_src_pathname : /home/site/domains/mydomain/public_html/images/tmp/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_src_mime : image/jpeg
    file_src_size : 118252 (max= 134217728)
    file_src_error : 0
- source file is an image
    image_src_x : 1280
    image_src_y : 720
    image_src_pixels : 921600
    image_src_type : jpg
    image_src_bits : 8
process file to /home/site/domains/mydomain/public_html/images/full/
- file size OK
- file mime OK : image/jpeg
- file name safe format
- destination variables
    file_dst_path : /home/site/domains/mydomain/public_html/images/full/
    file_dst_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_dst_pathname : /home/site/domains/mydomain/public_html/images/full/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg doesn't exist already
- EXIF data is invalid or missing
- no image processing wanted
- process OK
process file to /home/site/domains/mydomain/public_html/images/
- file size OK
- file mime OK : image/jpeg
- file name safe format
- destination variables
    file_dst_path : /home/site/domains/mydomain/public_html/images/
    file_dst_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_dst_pathname : /home/site/domains/mydomain/public_html/images/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg doesn't exist already
- EXIF data is invalid or missing
- image resizing or conversion wanted
- source image is JPEG
- setting destination file type to jpg
- resizing...
    calculate y size
    image_src_x y : 1280 x 720
    image_dst_x y : 2000 x 1125
    cancel resizing, as it would enlarge the image!
- add watermark
    watermark source image is PNG
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK
process file to /home/site/domains/mydomain/public_html/images/140/
- file size OK
- file mime OK : image/jpeg
- file name safe format
- destination variables
    file_dst_path : /home/site/domains/mydomain/public_html/images/140/
    file_dst_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_dst_pathname : /home/site/domains/mydomain/public_html/images/140/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg doesn't exist already
- EXIF data is invalid or missing
- image resizing or conversion wanted
- source image is JPEG
- setting destination file type to jpg
- resizing...
    ratio_crop_x : 46 (23;23)
    image_src_x y : 1280 x 720
    image_dst_x y : 186 x 105
    resized image object created
- crop image : 0 23 0 23 
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK

miniaturka zdjęcia 720p została utworzona i zapisana na serwerze
system information
- class version : 0.34dev
- operating system : Linux
- PHP version : 7.1.0
- GD version : 2.1.0
- supported image types : png jpg gif bmp
- open_basedir : no restriction
- upload_max_filesize : 128M (134217728 bytes)
- language : en_GB
source is a local file /home/site/domains/mydomain/public_html/images/tmp/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- local file OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    MAGIC path will not be used
    MIME type detected as image/jpeg; charset=binary by Fileinfo PECL extension
- MIME validated as image/jpeg
source variables
- You can use all these before calling process()
    file_src_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_src_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_src_name_ext : jpg
    file_src_pathname : /home/site/domains/mydomain/public_html/images/tmp/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_src_mime : image/jpeg
    file_src_size : 118252 (max= 134217728)
    file_src_error : 0
- source file is an image
    image_src_x : 1280
    image_src_y : 720
    image_src_pixels : 921600
    image_src_type : jpg
    image_src_bits : 8
process file to /home/site/domains/mydomain/public_html/images/full/
- file size OK
- file mime OK : image/jpeg
- file name safe format
- destination variables
    file_dst_path : /home/site/domains/mydomain/public_html/images/full/
    file_dst_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_dst_pathname : /home/site/domains/mydomain/public_html/images/full/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg doesn't exist already
- EXIF data is invalid or missing
- no image processing wanted
- process OK
process file to /home/site/domains/mydomain/public_html/images/
- file size OK
- file mime OK : image/jpeg
- file name safe format
- destination variables
    file_dst_path : /home/site/domains/mydomain/public_html/images/
    file_dst_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_dst_pathname : /home/site/domains/mydomain/public_html/images/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg doesn't exist already
- EXIF data is invalid or missing
- image resizing or conversion wanted
- source image is JPEG
- setting destination file type to jpg
- resizing...
    calculate y size
    image_src_x y : 1280 x 720
    image_dst_x y : 2000 x 1125
    cancel resizing, as it would enlarge the image!
- add watermark
    watermark source image is PNG
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK
process file to /home/site/domains/mydomain/public_html/images/140/
- file size OK
- file mime OK : image/jpeg
- file name safe format
- destination variables
    file_dst_path : /home/site/domains/mydomain/public_html/images/140/
    file_dst_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_dst_pathname : /home/site/domains/mydomain/public_html/images/140/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg doesn't exist already
- EXIF data is invalid or missing
- image resizing or conversion wanted
- source image is JPEG
- setting destination file type to jpg
- resizing...
    ratio_crop_x : 46 (23;23)
    image_src_x y : 1280 x 720
    image_dst_x y : 186 x 105
    resized image object created
- crop image : 0 23 0 23 
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK
process file to /home/site/domains/mydomain/public_html/images/720/
- file size OK
- file mime OK : image/jpeg
- file name safe format
- destination variables
    file_dst_path : /home/site/domains/mydomain/public_html/images/720/
    file_dst_name_body : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS
    file_dst_name_ext : jpg
- checking for auto_rename
- destination file details
    file_dst_name : Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
    file_dst_pathname : /home/site/domains/mydomain/public_html/images/720/Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg
- Skoda-Octavia-3-MY2015-car-logo-change-to-vRS-sprememba-grafike-avtomobila-na-RS.jpg doesn't exist already
- EXIF data is invalid or missing
- image resizing or conversion wanted
- source image is JPEG
- setting destination file type to jpg
- resizing...
    ratio_crop_x : 240 (120;120)
    image_src_x y : 1280 x 720
    image_dst_x y : 960 x 540
    resized image object created
- crop image : 0 120 0 120 
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK

**Comment by verot** [comment]
Are you using the latest version from _master_? Do you see this commit 98c187b79ad94372c7792aeb38c501ea0ff693ee in your version of the class?

**Comment by verot** [comment]
It is 0.34dev, but is it the last code from _master_?

**Comment by CNK001** [comment]
Wow, ok, I updated class.upload.php and now there is no error, thanks you!

**Comment by verot** [comment]
No problems! Closing.

**Comment by wiwi1234** [comment]
I solved the same problems by updating , Thanks a lot!!
