### ISSUE TITLE
incompatibility with versions major than PHP v7.1.0 

### ISSUE THREAD

**Issue by EneasVVA** [verot/class.upload.php#64]
A non well formed numeric value encountered
\vendor\verot\class.upload.php\src\class.upload.php:2678
\vendor\verot\class.upload.php\src\class.upload.php:1725
\vendor\verot\class.upload.php\src\class.upload.php:2067
\vendor\verot\class.upload.php\src\class.upload.php:2004

**Comment by verot** [comment]
Which version of the class are you using? The line numbers you provide don't match with _master_

**Comment by EneasVVA** [comment]
right, I was going to correct with a pull request but it's fixed in dev-master release, please, fix it in stable versions.
