### ISSUE TITLE
EXIF Auto-orientaion results in a PHP timeout

### ISSUE THREAD

**Issue by Mouradlayouni** [verot/class.upload.php#67]
The EXIF Auto-orientaion results in a PHP timeout with an image of 2300px/4100px and size of 2.4 MB.

**Comment by verot** [comment]
If the class works with [this image](https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_6.jpg), then it means that your image is too large to be processed by the class.

You can deactivate automatic rotation by setting _image_auto_rotate_ to false.

**Comment by Mouradlayouni** [comment]
I set image_auto_rotateto false and added this code before processing the image with the class:

$imageSourceName = $_FILES[input_name']['tmp_name'];
$exif = read_exif_data($imageSourceName);
				
if(!empty($exif['Orientation']))
{
	$tempImage = imagecreatefromjpeg($imageSourceName);
	switch ($exif['Orientation'])
	{
	        case 3:
		$tempImage = imagerotate($tempImage, 180, 0);
		break;
						
		case 6:
		$tempImage = imagerotate($tempImage, -90, 0);
		break;
					
		case 8:
		$tempImage = imagerotate($tempImage, 90, 0);
		break;
	}
	imagejpeg($tempImage, $imageSourceName, 70);
	imagedestroy($tempImage);
}
