### ISSUE TITLE
Base64 encoded image does not seem to work

### ISSUE THREAD

**Issue by coffeverton** [verot/class.upload.php#68]
My html form uploads a base64 encoded string.
When I try to process the string (using the 'base64' keyword), the class does not resize my image.
If i create a tmp file, put the base64 decoded string on it, and then process it with the class, then it works.

When debugging, i found out that the attribute $file_is_image of the class is not true, when it parses the base64 encoded string.

This is the result log:
<b>system information</b>
<br />-&nbsp;class version           : 0.34dev
<br />-&nbsp;operating system        : Linux
<br />-&nbsp;PHP version             : 5.6.27-1+deb.sury.org~xenial+1
<br />-&nbsp;GD version              : 2.2.3
<br />-&nbsp;supported image types   : png jpg gif bmp
<br />-&nbsp;open_basedir            : no restriction
<br />-&nbsp;upload_max_filesize     : 2M (2097152 bytes)
<br />-&nbsp;language                : en_GB
<br /><b>source is a base64 data string of length 13672</b>
<br />- requires a temp file ...  file created
<br />&nbsp;&nbsp;&nbsp;&nbsp;temp file is: /tmp/02f9e3d4ffc9f0a9c35edf8ef56c4e99
<br />- local file OK
<br /><b>determining MIME type</b>
<br />- Checking MIME type with Fileinfo PECL extension
<br />&nbsp;&nbsp;&nbsp;&nbsp;MAGIC path will not be used
<br />&nbsp;&nbsp;&nbsp;&nbsp;MIME type detected as application/octet-stream; charset=binary by Fileinfo PECL extension
<br />-&nbsp;MIME validated as application/octet-stream
<br />- Flash may be rewriting MIME as application/octet-stream
<br />- Try to guess MIME type from file extension (): doesn't look like anything known
<br /><b>source variables</b>
<br />- You can use all these before calling process()
<br />&nbsp;&nbsp;&nbsp;&nbsp;file_src_name         : base64
<br />&nbsp;&nbsp;&nbsp;&nbsp;file_src_name_body    : base64
<br />&nbsp;&nbsp;&nbsp;&nbsp;file_src_name_ext     : 
<br />&nbsp;&nbsp;&nbsp;&nbsp;file_src_pathname     : /tmp/02f9e3d4ffc9f0a9c35edf8ef56c4e99
<br />&nbsp;&nbsp;&nbsp;&nbsp;file_src_mime         : application/octet-stream
<br />&nbsp;&nbsp;&nbsp;&nbsp;file_src_size         : 13672 (max= 2097152)
<br />&nbsp;&nbsp;&nbsp;&nbsp;file_src_error        : 0
<br /><b>process file to /myapplicationdir/application/../resources/uploads/2017/03/29/</b>
<br />- file size OK
<br />- script renamed as base64.txt!
<br />- file mime OK : text/plain
<br />- new file name body : 58dbd25484c64
<br />- new file name ext : jpg
<br />- file name safe format
<br />- destination variables
<br />&nbsp;&nbsp;&nbsp;&nbsp;file_dst_path         : /myapplicationdir/application/../resources/uploads/2017/03/29/
<br />&nbsp;&nbsp;&nbsp;&nbsp;file_dst_name_body    : 58dbd25484c64
<br />&nbsp;&nbsp;&nbsp;&nbsp;file_dst_name_ext     : jpg
<br />- checking for auto_rename
<br />- destination file details
<br />&nbsp;&nbsp;&nbsp;&nbsp;file_dst_name         : 58dbd25484c64.jpg
<br />&nbsp;&nbsp;&nbsp;&nbsp;file_dst_pathname     : /myapplicationdir/application/../resources/uploads/2017/03/29/58dbd25484c64.jpg
<br />- 58dbd25484c64.jpg doesn't exist already
<br />- auto-rotate applies only to JPEG images
<br />- no image processing wanted
<br />- <b>process OK</b>
<br />

**Comment by verot** [comment]
For some reason, the MIME type of the base64 string (in the temporary file) is incorrectly detected:
> MIME type detected as application/octet-stream; charset=binary by Fileinfo PECL extension

For that reason, the class doesn't recognize the file as an image.

What is your base64 string? Does it work when you copy it in the [test suite](https://github.com/verot/class.upload.php/tree/master/test)?

**Comment by coffeverton** [comment]
I see it now.
My string starts with "data:image/jpeg;base64,". If I remove this part, the mime type gets detected, and it works.

My bad.
Thanks for the help!
