### ISSUE TITLE
upload base64 file,I get the Error: Can't create the temporary file. 

### ISSUE THREAD

**Issue by hawkcraw** [verot/class.upload.php#71]
when I use base64
content : "data:image/png;base64,**********"
I get the error:Error: Can't create the temporary file. Can't carry on a process.

use this content : "**********"
success. why?

**Comment by verot** [comment]
Can you copy here the logs produced by the class?

**Comment by hawkcraw** [comment]
sorry,
class.upload.php test forms

File not uploaded on the server
Error: Can't create the temporary file. Can't carry on a process.

do another test

system information
- class version           : 0.34dev
- operating system        : WINNT
- PHP version             : 5.6.15
- GD version              : 2.1.0
- supported image types   : png jpg gif bmp
- open_basedir            : no restriction
- upload_max_filesize     : 2M (2097152 bytes)
- language                : en_GB
source is a base64 data string of length 0
- requires a temp file ...  failed

**Comment by hawkcraw** [comment]
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACUAAAARCAYAAABadWW4AAAABmJLR0QAAAAAAAD5Q7t/AAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4AoBFik0VcV6egAAALpJREFUSMftlk0KwyAUhMfSTRDP4ybkFgGPqSRHUvAW001TWpqnFgykkIG3iT/fqGNQkSROphtOqJcppdRHGWMwTRPWdf0atPWRJLU3M/gUALFCCHzX9l2S1N7KgDRRjJHzPBMArbVdTdUYKE2UcyYADsNwiCmJUQx6KTe9tMuQVpFSonOueHy1qu2UxGgKuve+q6kaQzSlteY4jlyWpTkzv94+iXHfOc7Dc1RjnPuPfpn6R1Pqero06gEPaFNPl21bvgAAAABJRU5ErkJggg==

**Comment by verot** [comment]
You are in fact supposed to input only the base64 data, not the whole string (so starting with `iVBOR`...)

I just pushed 000be61326e82e773f5cdc48a9dd18ce3d86bd50 so that a better error message is provided when the data is invalid. Besides, you can now input the whole string starting with `data:`... The class will sort it out.
