### ISSUE TITLE
PNG Read Error: truncated data

### ISSUE THREAD

**Issue by leventmenekse** [verot/class.upload.php#78]
We use this library for upload user's images but sometimes they send us broken images and we get error like:

> imagecreatefrompng(): gd-png: fatal libpng error: Read Error: truncated data

Apparently adding `@`  beginning of the function can't handle this.

We tried to catch it but because it is fatal error we can't suppress it. Any idea to work this out ? We want to catch this error and send custom message to the users.

Thanks!

**Comment by verot** [comment]
Can you send me one of these PNG images? And which version of GD are you using, and which operating system?

**Comment by leventmenekse** [comment]
It is gd2 function php 5.6 on ubuntu server and one of the image they try to upload is:

https://www.kimarar.com/image/data/resimler/gokkusagi-mat-paspas-1256.png

**Comment by verot** [comment]
Yes, these images are indeed broken:
```
$ pngcheck -vt gokkusagi-mat-paspas-1256.png 
File: gokkusagi-mat-paspas-1256.png (90112 bytes)
  chunk IHDR at offset 0x0000c, length 13
    500 x 500 image, 32-bit RGB+alpha, non-interlaced
  chunk sRGB at offset 0x00025, length 1
    rendering intent = perceptual
  chunk gAMA at offset 0x00032, length 4: 0.45455
  chunk pHYs at offset 0x00042, length 9: 3779x3779 pixels/meter (96 dpi)
  chunk IDAT at offset 0x00057, length 65445
    zlib: deflated, 32K window, fast compression
  chunk IDAT at offset 0x10008, length 65524:  EOF while reading data
ERRORS DETECTED in gokkusagi-mat-paspas-1256.png
```
And PHP is crashing on these images, it is a fatal error... You cannot even catch it with `try/catch`. From PHP 5.2, you can try to catch it with `register_shutdown_function`, but that's about all.

So I think the only solution would be to check the images beforehand, maybe with `pngcheck`, but it has to be done outside of the class, and it is not very handy when uploading...

**Comment by leventmenekse** [comment]
I see, well then we are looking into `pngcheck`

Thanks!

**Comment by larimmisha** [comment]
![580265b901b80](https://user-images.githubusercontent.com/17030521/50363502-be22f380-058d-11e9-88df-9fb441deee36.jpg)
Вот еще один подобных файл, на своём сервере я с десяток таких файлов отловил которые положили скрипты переноса сайта + сжатие файлов происходило. Приходилось отлавливать такие файлы и отдельно с ними решать их судьбу.
