### ISSUE TITLE
Invalid character use in regular expressions

### ISSUE THREAD

**Issue by ReneBakkerBBIT** [verot/class.upload.php#79]
In class.upload.php regular expressions sometimes make use of character sets, e.g.
```
if (preg_match("/^([\.-\w]+)\/([\.-\w]+)(.*)$/i", $this->file_src_mime)) { 
   ...
}
```
The problem is that \w is not a valid use in regexp character sets, and issues PHP warnings if executed.

Could you please rewrite these (multiple) regexp's in a new version?
Thx in advance.

**Comment by ReneBakkerBBIT** [comment]
I would happily make some changes myself (awaiting a new version), but the problem is: I do not know which character (instead of \w) was intended to close off the character range originally.

**Comment by verot** [comment]
Which version of PHP are you using? And which version of the class? Can you copy here the warnings?

**Comment by ReneBakkerBBIT** [comment]
Hi Colin,

Thanks for picking up on this issue. Here is the requested info:

[cid:image001.png@01D32337.87D82820]

[cid:image002.png@01D32337.87D82820]

[cid:image003.png@01D32338.017CE760]

[cid:image004.png@01D32338.017CE760]

Met vriendelijke groet,
René Bakker

Van: Colin Verot [mailto:notifications@github.com]
Verzonden: vrijdag 1 september 2017 15:00
Aan: verot/class.upload.php <class.upload.php@noreply.github.com>
CC: René Bakker <rb@bbit.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [verot/class.upload.php] Invalid character use in regular expressions (#79)


Which version of PHP are you using? And which version of the class? Can you copy here the warnings?

**Comment by verot** [comment]
There are no images in your email and post, they didn't get attached

**Comment by ReneBakkerBBIT** [comment]
Colin,

Hereby I put them in a Word document …

Met vriendelijke groet/dear regards,
René Bakker

Van: Colin Verot [mailto:notifications@github.com]
Verzonden: vrijdag 1 september 2017 16:36
Aan: verot/class.upload.php <class.upload.php@noreply.github.com>
CC: René Bakker <rb@bbit.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [verot/class.upload.php] Invalid character use in regular expressions (#79)


There are no images in your email and post, they didn't get attached

**Comment by verot** [comment]
You cannot attach documents or images in ticket issues by email. Besides, Word is a proprietary format, it is better to use LibreOffice for instance.

But more simply, you can just copy and paste here:
- PHP version
- class version
- warning messages

**Comment by verot** [comment]
I am not sure where your warnings are coming from. `\w` is a [valid regex escape sequence](http://php.net/manual/en/regexp.reference.escape.php). It is used to match MIME types, which can be a word, a dot or a dash.

**Comment by ReneBakkerBBIT** [comment]
Hi Colin,

It turned out I used an older version of class.upload.php, namely 032.

Regexp’s in that version contained:

[\.-\w]

After updating to the latest version from github, the same regexp’s contain:

                [\.\w-]

which do *not* result in errors anymore.

Possible explanation i.m.h.o:

The 032 version expresssion is interpreted as a range, ranging from a dot to  \w; but \w is not just one character, but matches whole words -as you rightly indicated before-, so at compile time the regexp interpretor was unable to determine a valid range.

The github/latest version is interpreted as a collection, consisting of a dot, a word or a dash, resulting in a valid regexp.

I hope this makes any sense to you.
Anyway: thanks for your time!

Van: Colin Verot [mailto:notifications@github.com]
Verzonden: zaterdag 2 september 2017 1:41
Aan: verot/class.upload.php <class.upload.php@noreply.github.com>
CC: René Bakker <rb@bbit.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [verot/class.upload.php] Invalid character use in regular expressions (#79)


I am not sure where your warnings are coming from. \w is a valid regex escape sequence<http://php.net/manual/en/regexp.reference.escape.php>. It is used to match MIME types, which can be a word, a dot or a dash.
