### ISSUE TITLE
It automatically rotates some images

### ISSUE THREAD

**Issue by ebbbang** [verot/class.upload.php#8]
This is my code -
```
foreach ($images as $image)
{
	$handle = new upload($image);
	if ($handle->uploaded)
	{
		$handle->file_new_name_body   = 'image_resized';
		$handle->image_resize         = true;
		$handle->image_x              = 1170;
		$handle->image_ratio_y        = true;
		$handle->process('/images/web_launch/processed/');
		if($handle->processed)
		{
			echo 'image resized<br>';
			// $handle->clean();
		}
		else
		{
			echo 'error : ' . $handle->error."<br>";
		}
	}
}
```
The conversion and compression is working fine but it automatically rotates some images 90 degrees anti-clock wise .

**Comment by verot** [comment]
You can output the logs produced by the class, to see whether it does rotate the image or not.
Indeed, it is likely that the class doesn't rotate the images. In fact, the software that you use to visualize your original image probably rotates the image for you, using EXIF orientation data. And when you resize the image with the class, the EXIF information is discarded, and the image is not roatated automatically in your image browser.
Use a different software to visualize the images; or make sure your software doesn't auto-rotate the images.
Note that the detection of image rotation is planned for a future version of the class.

**Comment by ebbbang** [comment]
You are right it's the EXIF issue. I figured out a way to re-orient the image first then go through your class. Works like a charm now .

**Comment by ebbbang** [comment]
You can use it in your next class update 

function image_fix_orientation($filename)
	{
	    $exif = exif_read_data($filename);
	    if (!empty($exif['Orientation']))
	    {
	        $image = imagecreatefromjpeg($filename);
	        switch ($exif['Orientation'])
	        {
	            case 3:
	                $image = imagerotate($image, 180, 0);
	                break;

	            case 6:
	                $image = imagerotate($image, -90, 0);
	                break;

	            case 8:
	                $image = imagerotate($image, 90, 0);
	                break;
	        }

	        imagejpeg($image, $filename, 90);
	    }
	}

**Comment by verot** [comment]
Thank you.

**Comment by logicandluck** [comment]
Thank you, @ebbbang. This helped me find what I needed to do. @verot, you say use a different software to visualize the images. My issue was with iPhone camera, sending images back, rotated after a resize because the exif data was deleted. But my original saved image, before resize was correct. This seems like a good user experience to have.

Great job & thank you for your hard work.

**Comment by risingisland** [comment]
Where does one add this code?
I am having the same problem, photos taken with an iPhone are changing their orientation after upload.

**Comment by ebbbang** [comment]
Just call the function on the uploaded image. It would be re-oriented on the original file.

**Comment by verot** [comment]
The class now implements automatic rotation of the image according to EXIF data
