### ISSUE TITLE
Failed Mime Type Check For DOCX Files

### ISSUE THREAD

**Issue by muratgozel** [verot/class.upload.php#80]
Hey,

First of all, I am thankful to the author of this library because I'm using it for years in my PHP dev environment.

Today I've narrowed the list of allowed mime types in a form that people can upload their cv's.
```php
$handle->allowed = array("application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/rtf", "application/pdf");
```

This should accept **doc, docx, pdf and rtf** files only.

I am able to upload pdf, rtf and doc files successfully. And library raises an error if I try to upload any type of image files. But it also raises an error if I try to upload **docx** files. Error that says:
```
Incorrect type of file.
```

I tried to read file_src_mime variable after process() and it gives **application/zip**.

I've tried different docx files but same thing happened. My code is very simple. Only **file_max_size** and **file_new_name_body** are updated before process being called. I've also tried to detect mime type of docx file from command line in my computer:
```sh
> file -I ps_org_chart_instructions.docx
ps_org_chart_instructions.docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document; charset=binary
```

Here is what class logs:
```
system information
- class version : 0.34dev
- operating system : Linux
- PHP version : 5.3.3-7+squeeze28
- GD version : 2.0
- supported image types : png jpg gif bmp
- open_basedir : /home/.../httpdocs:/home/.../tmp:/tmp:/home/.../moodledata
- upload_max_filesize : 32M (33554432 bytes)
- language : en_GB
source is an uploaded file
- upload OK
- file name OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    MAGIC path will not be used
    MIME type detected as application/zip; charset=binary by Fileinfo PECL extension
- MIME validated as application/zip
source variables
- You can use all these before calling process()
    file_src_name : ps_org_chart_instructions.docx
    file_src_name_body : ps_org_chart_instructions
    file_src_name_ext : docx
    file_src_pathname : /home/.../tmp/phpZGWlim
    file_src_mime : application/zip
    file_src_size : 821669 (max= 33554432)
    file_src_error : 0
process file to ../docs/cv/
- file size OK
- error: Incorrect type of file.
```

**Comment by verot** [comment]
It is normal. These files are actually ZIP files. And there aren't any good methods to get around that.

You may try to deactivate _Fileinfo_ in the class, to use other MIME detection methods. Set to false here:
`$this->mime_fileinfo            = false;     // MIME detection with Fileinfo PECL extension`

**Comment by muratgozel** [comment]
This looks weird. I've written a quick fix to cover this situation for now.
```php
if ($handle->file_src_name_ext == 'docx') {
  $handle->allowed = array("application/msword", "application/zip", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/rtf", "application/pdf");
} else {
  $handle->allowed = array("application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/rtf", "application/pdf");
}
```
Thanks for the information. 👍
