### ISSUE TITLE
Crop the center of the image without resizing

### ISSUE THREAD

**Issue by IndiAsh** [verot/class.upload.php#83]
Is there anyway so i can get the center of the image cropped? 
I have an image 600  x 1200 and i want to get 20 x 20 from the center of the image. I don't want the image to be resized.

**Comment by verot** [comment]
Yes, you can. Upon instantiating the class with your image, you can read `image_src_x` and `image_src_y`. With these values, you can set `image_ratio_crop` or `image_crop` and call `process()`
