### ISSUE TITLE
how to set permissions when uploading a file recursively to the file and directory

### ISSUE THREAD

**Issue by themhz** [verot/class.upload.php#87]
This is what I do

        $status = false;
        $message = "";
        $handle = new upload($_FILES['image_field']);

        if ($handle->uploaded) {
            $handle->image_resize         = true;
            $handle->image_ratio_y        = true;
            $handle->file_overwrite       = true;            
            
            $handle->process(getcwd().'/../accountfiles/ac_'.accountHandler::$id.'/classes/');            
            if ($handle->processed) {
                $status = true;
                $message = $handle->file_src_name;
                
                $handle->clean();

But the permission on the server when uploaded is 777. I need to change it to 755 for folders and 644 to the file. How can I do this?

**Comment by verot** [comment]
Check out the parameter _dir_chmod_ in the documentation

**Comment by themhz** [comment]
Thank you but it doesn't seem to do it recursively and the permission created are 
d-wxrw--wt 2 www-data www-data 4096 Jan  6 13:22 classes
It creates the folder with those permissions

**Comment by verot** [comment]
I am not sure which value you give to _dir_chmod_. But the class, if it needs to create (or make writeable) a directory, uses _dir_chmod_. There is no permissions set on the uploaded files themselves (which you can do easily out of the class). 

So if a directory needs to be created _dir_chmod_ is used, but bear in mind that the host system might not allow all permissions to be set by the web server user.

**Comment by themhz** [comment]
$status = false;
        $message = "";
        $handle = new upload($_FILES['image_field']);

        if ($handle->uploaded) {            
            $handle->image_resize         = true;            
            $handle->image_ratio_y        = true;
            $handle->file_overwrite       = true;
            $handle->dir_chmod            = 755;
            
            $handle->process(getcwd().'/../accountfiles/ac_'.accountHandler::$id.'/classes/');            
            if ($handle->processed) {
                $status = true;
                $message = $handle->file_src_name;
                
                $handle->clean();

**Comment by verot** [comment]
Then use _dir_chmod_ for the directory, if it happens to be created by the class.

As for the files, change their permissions via PHP, after calling the class. The file name is in _file_dst_pathname_ or _file_dst_name_

**Comment by themhz** [comment]
Oh you are right. My bad, I misspelled the 755, it should be 0755 $handle->dir_chmod            = 0755;
Now the permissions are correct . However I am not sure about the file. it is in -rw-r--r-- So I guess I am good Thank you
