### ISSUE TITLE
upload base64 decode error

### ISSUE THREAD

**Issue by aragoneca** [verot/class.upload.php#88]
I would like to report a possible bug
Today i updated with the last version of the upload class but i had a problem with given base64 of image - i was not uploaded at all and i started to debug and i found why:
In the 000be61 from Jun 2, 2017, you changed the handling of base64, after some debugging i realised that the regex is not correct.
since you changed line 2213:
$data = base64_decode(preg_replace('/^base64:(.*)/i', '$1', $file));
with:
$data = base64_decode(preg_replace('/^base64:(?:.base64,)?(.)/i', '$1', $file));

$data is always null, i tried with many files, they are processed in the old way, but not in the new one, after changing with the old regex become fine.
You can test the regex here and see the result, without touching your code:
Old: https://regex101.com/r/i9TbSl/1/
New: https://regex101.com/r/PNOlZs/1

The result is in right: "Match Information", its cut the whole string after "base64:"

**Comment by verot** [comment]
Fixed in d63b7568513edb5947ddd77ff082e6258796244b. Thanks for reporting!
