### ISSUE TITLE
My files seems to be inaccessible after saving them.

### ISSUE THREAD

**Issue by Jevison7x** [verot/class.upload.php#92]
Please view full details of my issues [here](https://stackoverflow.com/questions/50534903/php-uploaded-file-cannot-be-accessed-not-found-after-it-was-uploaded/50535831?noredirect=1#comment88084469_50535831)

**Comment by verot** [comment]
As the StackOverflow says, it is likely an ownership issue. In other words, it is likely a web server configuration issue, and not a class issue.
Try uploading the whole class package on your webserver, and test what is inside the `test/` directory. The test should always work.
